[Ic4a]
Meter=Shape
MeterStyle=BRG|PG3|CSTI
Y=300
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Config\ColorSpectrum" "Config.ini"]

[Imcs4]
Meter=Shape
MeterStyle=IMS|PG3
X=166
Y=300

[IP54]
Meter=Shape
MeterStyle=PF1|PG3
Shape=Rectangle 0,0,44,14,2 | Fill LinearGradient GradientClo | Extend BallsClo
X=115
Y=300

[IP54Co]
Meter=Shape
MeterStyle=PF1|PG3
Shape=Rectangle 0,0,65,14,2 | Fill LinearGradient GradientClo | Extend BallsClo
X=210
Y=300

[Colo4]
Meter=String
MeterStyle=Style|STTI|PG3
Text=#T2P9#4: 
Y=301
UpdateDivider=-1

[CurC4]
Meter=Image
MeterStyle=CT
SolidColor=#FBP#
X=50r
Y=2r

[CColo4]
Meter=String
MeterStyle=Style|PG3
Text=#OACT# 
X=210
Y=-3r

[F125]
Meter=Image
MeterStyle=C125|STPC
X=117
Y=23r
LeftMouseUpAction=[#VVS# "FBP" "255,255,250" #@#Style.inc]#MTAJR1##Couq1#

[F225]
Meter=Image
MeterStyle=C225|STPC
LeftMouseUpAction=[#VVS# "FBP" "255,255,0" #@#Style.inc]#MTAJR1##Couq2#

[F325]
Meter=Image
MeterStyle=C325|STPC
LeftMouseUpAction=[#VVS# "FBP" "255,153,0,255" #@#Style.inc]#MTAJR1##Couq3#

[F425]
Meter=Image
MeterStyle=C425|STPC
LeftMouseUpAction=[#VVS# "FBP" "255,27,10" #@#Style.inc]#MTAJR1##Couq4#

[F525]
Meter=Image
MeterStyle=C525|STPC
LeftMouseUpAction=[#VVS# "FBP" "255,0,255" #@#Style.inc]#MTAJR1##Couq5#

[F623]
Meter=Image
MeterStyle=C623|STPC
LeftMouseUpAction=[#VVS# "FBP" "236,0,140" #@#Style.inc]#MTAJR1##Couq6#

[F720]
Meter=Image
MeterStyle=C720|STPC
LeftMouseUpAction=[#VVS# "FBP" "201,255,92, 255" #@#Style.inc]#MTAJR1##Couq7#

[F818]
Meter=Image
MeterStyle=C818|STPC
LeftMouseUpAction=[#VVS# "FBP" "187,187,176,255" #@#Style.inc]#MTAJR1##Couq8#

[F916]
Meter=Image
MeterStyle=C916|STPC
LeftMouseUpAction=[#VVS# "FBP" "161,0,253" #@#Style.inc]#MTAJR1##Couq9#

[F1014]
Meter=Image
MeterStyle=C1014|STPC
LeftMouseUpAction=[#VVS# "FBP" "140,220,57" #@#Style.inc]#MTAJR1##Couq10#

[F8201]
Meter=Image
MeterStyle=T101|STPC
LeftMouseUpAction=[#VVS# "FBP" "161,0,79" #@#Style.inc]#MTAJR1##Couq11#

[F111]
Meter=Image
MeterStyle=C111|STPC
LeftMouseUpAction=[#VVS# "FBP" "134,108,155" #@#Style.inc]#MTAJR1##Couq12#

[F211]
Meter=Image
MeterStyle=T111|STPC
LeftMouseUpAction=[#VVS# "FBP" "252,252,252" #@#Style.inc]#MTAJR1##Couq13#

[F121]
Meter=Image
MeterStyle=C121|STPC
X=117
Y=15r
LeftMouseUpAction=[#VVS# "FBP" "130, 227, 113, 89" #@#Style.inc]#MTAJR1##Couq14#

[F131]
Meter=Image
MeterStyle=C131|STPC
LeftMouseUpAction=[#VVS# "FBP" "128,128,64" #@#Style.inc]#MTAJR1##Couq15#

[F141]
Meter=Image
MeterStyle=C141|STPC
LeftMouseUpAction=[#VVS# "FBP" "128,64,0,255" #@#Style.inc]#MTAJR1##Couq16#

[F159]
Meter=Image
MeterStyle=C159|STPC
LeftMouseUpAction=[#VVS# "FBP" "98,46,105" #@#Style.inc]#MTAJR1##Couq17#

[F166]
Meter=Image
MeterStyle=C166|STPC
LeftMouseUpAction=[#VVS# "FBP" "64,128,128" #@#Style.inc]#MTAJR1##Couq18#

[F176]
Meter=Image
MeterStyle=C176|STPC
LeftMouseUpAction=[#VVS# "FBP" "64,0,128" #@#Style.inc]#MTAJR1##Couq19#

[F184]
Meter=Image
MeterStyle=C184|STPC
LeftMouseUpAction=[#VVS# "FBP" "64,153,224" #@#Style.inc]#MTAJR1##Couq20#

[F1901]
Meter=Image
MeterStyle=C1901|STPC
LeftMouseUpAction=[#VVS# "FBP" "0, 171, 255, 255" #@#Style.inc]#MTAJR1##Couq21#

[F2001]
Meter=Image
MeterStyle=C2001|STPC
LeftMouseUpAction=[#VVS# "FBP" "0,128,192" #@#Style.inc]#MTAJR1##Couq22#

[F2101]
Meter=Image
MeterStyle=C2101|STPC
LeftMouseUpAction=[#VVS# "FBP" "0,128,0" #@#Style.inc]#MTAJR1##Couq23#

[F2200]
Meter=Image
MeterStyle=C2200|STPC
LeftMouseUpAction=[#VVS# "FBP" "0,0,255" #@#Style.inc]#MTAJR1##Couq24#

[F8230]
Meter=Image
MeterStyle=C230|STPC
LeftMouseUpAction=[#VVS# "FBP" "0,0,0" #@#Style.inc]#MTAJR1##Couq25#

[F8235]
Meter=Image
MeterStyle=T230|STPC
LeftMouseUpAction=[#VVS# "FBP" "60,60,60" #@#Style.inc]#MTAJR1##Couq26#

[T4521]
Meter=Image
MeterStyle=T121|STPC
X=117
Y=15r
LeftMouseUpAction=[#VVS# "FBP" "225,225,225" #@#Style.inc]#MTAJR1##Couq27#

[V6230]
Meter=Image
MeterStyle=V230|STPC
LeftMouseUpAction=[#VVS# "FBP" "102,131,144" #@#Style.inc]#MTAJR1##Couq28#

[V6240]
Meter=Image
MeterStyle=V240|STPC
LeftMouseUpAction=[#VVS# "FBP" "208,52,56" #@#Style.inc]#MTAJR1##Couq29#

[V6250]
Meter=Image
MeterStyle=V250|STPC
LeftMouseUpAction=[#VVS# "FBP" "253,108,63" #@#Style.inc]#MTAJR1##Couq30#

[V6260]
Meter=Image
MeterStyle=V260|STPC
LeftMouseUpAction=[#VVS# "FBP" "249,78,124" #@#Style.inc]#MTAJR1##Couq31#

[V6270]
Meter=Image
MeterStyle=V270|STPC
LeftMouseUpAction=[#VVS# "FBP" "164,52,99" #@#Style.inc]#MTAJR1##Couq32#

[V6280]
Meter=Image
MeterStyle=V280|STPC
LeftMouseUpAction=[#VVS# "FBP" "219,179,40" #@#Style.inc]#MTAJR1##Couq33#

[V6290]
Meter=Image
MeterStyle=V290|STPC
LeftMouseUpAction=[#VVS# "FBP" "161,197,4" #@#Style.inc]#MTAJR1##Couq34#

[V6300]
Meter=Image
MeterStyle=V300|STPC
LeftMouseUpAction=[#VVS# "FBP" "33,115,70" #@#Style.inc]#MTAJR1##Couq35#

[V6310]
Meter=Image
MeterStyle=V310|STPC
LeftMouseUpAction=[#VVS# "FBP" "47,210,6" #@#Style.inc]#MTAJR1##Couq36#

[V6320]
Meter=Image
MeterStyle=V320|STPC
LeftMouseUpAction=[#VVS# "FBP" "3,208,252" #@#Style.inc]#MTAJR1##Couq37#

[V6330]
Meter=Image
MeterStyle=V330|STPC
SolidColor=52,92,252
LeftMouseUpAction=[#VVS# "FBP" "52,92,252" #@#Style.inc]#MTAJR1##Couq38#

[V6340]
Meter=Image
MeterStyle=V340|STPC
LeftMouseUpAction=[#VVS# "FBP" "57,64,197" #@#Style.inc]#MTAJR1##Couq39#