[Ic3a]
Meter=Shape
MeterStyle=BRG|PG3|CSTI
Y=224
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Config\ColorSpectrum" "Config.ini"]

[Imcs3]
Meter=Shape
MeterStyle=IMS|PG3
X=166
Y=224

[IP53]
Meter=Shape
MeterStyle=PF1|PG3
Shape=Rectangle 0,0,44,14,2 | Fill LinearGradient GradientClo | Extend BallsClo
X=115
Y=224

[IP53Co]
Meter=Shape
MeterStyle=PF1|PG3
Shape=Rectangle 0,0,65,14,2 | Fill LinearGradient GradientClo | Extend BallsClo
X=210
Y=224

[Colo3]
Meter=String
MeterStyle=Style|STTI|PG3
Text=#T2P9#3: 
Y=225
UpdateDivider=-1

[CurC3]
Meter=Image
MeterStyle=CT
SolidColor=#FBC#
X=50r
Y=2r

[CColo3]
Meter=String
MeterStyle=Style|PG3
Text=#OACT# 
X=210
Y=-3r

[E125]
Meter=Image
MeterStyle=C125|STPC
X=117
Y=23r
LeftMouseUpAction=[#VVS# "FBC" "255,255,250" #@#Style.inc]#MTAJR1##Coup1#

[E225]
Meter=Image
MeterStyle=C225|STPC
LeftMouseUpAction=[#VVS# "FBC" "255,255,0" #@#Style.inc]#MTAJR1##Coup2#

[E325]
Meter=Image
MeterStyle=C325|STPC
LeftMouseUpAction=[#VVS# "FBC" "255,153,0,255" #@#Style.inc]#MTAJR1##Coup3#

[E425]
Meter=Image
MeterStyle=C425|STPC
LeftMouseUpAction=[#VVS# "FBC" "255,27,10" #@#Style.inc]#MTAJR1##Coup4#

[E525]
Meter=Image
MeterStyle=C525|STPC
LeftMouseUpAction=[#VVS# "FBC" "255,0,255" #@#Style.inc]#MTAJR1##Coup5#

[E623]
Meter=Image
MeterStyle=C623|STPC
LeftMouseUpAction=[#VVS# "FBC" "236,0,140" #@#Style.inc]#MTAJR1##Coup6#

[E720]
Meter=Image
MeterStyle=C720|STPC
LeftMouseUpAction=[#VVS# "FBC" "201,255,92, 255" #@#Style.inc]#MTAJR1##Coup7#

[E818]
Meter=Image
MeterStyle=C818|STPC
LeftMouseUpAction=[#VVS# "FBC" "187,187,176,255" #@#Style.inc]#MTAJR1##Coup8#

[E916]
Meter=Image
MeterStyle=C916|STPC
LeftMouseUpAction=[#VVS# "FBC" "161,0,253" #@#Style.inc]#MTAJR1##Coup9#

[E1014]
Meter=Image
MeterStyle=C1014|STPC
LeftMouseUpAction=[#VVS# "FBC" "140,220,57" #@#Style.inc]#MTAJR1##Coup10#

[E8201]
Meter=Image
MeterStyle=T101|STPC
LeftMouseUpAction=[#VVS# "FBC" "161,0,79" #@#Style.inc]#MTAJR1##Coup11#

[E111]
Meter=Image
MeterStyle=C111|STPC
LeftMouseUpAction=[#VVS# "FBC" "134,108,155" #@#Style.inc]#MTAJR1##Coup12#

[E211]
Meter=Image
MeterStyle=T111|STPC
LeftMouseUpAction=[#VVS# "FBC" "252,252,252" #@#Style.inc]#MTAJR1##Coup13#

[E121]
Meter=Image
MeterStyle=C121|STPC
X=117
Y=15r
LeftMouseUpAction=[#VVS# "FBC" "130, 227, 113, 89" #@#Style.inc]#MTAJR1##Coup14#

[E131]
Meter=Image
MeterStyle=C131|STPC
LeftMouseUpAction=[#VVS# "FBC" "128,128,64" #@#Style.inc]#MTAJR1##Coup15#

[E141]
Meter=Image
MeterStyle=C141|STPC
LeftMouseUpAction=[#VVS# "FBC" "128,64,0,255" #@#Style.inc]#MTAJR1##Coup16#

[E159]
Meter=Image
MeterStyle=C159|STPC
LeftMouseUpAction=[#VVS# "FBC" "98,46,105" #@#Style.inc]#MTAJR1##Coup17#

[E166]
Meter=Image
MeterStyle=C166|STPC
LeftMouseUpAction=[#VVS# "FBC" "64,128,128" #@#Style.inc]#MTAJR1##Coup18#

[E176]
Meter=Image
MeterStyle=C176|STPC
LeftMouseUpAction=[#VVS# "FBC" "64,0,128" #@#Style.inc]#MTAJR1##Coup19#

[E184]
Meter=Image
MeterStyle=C184|STPC
LeftMouseUpAction=[#VVS# "FBC" "64,153,224" #@#Style.inc]#MTAJR1##Coup20#

[E1901]
Meter=Image
MeterStyle=C1901|STPC
LeftMouseUpAction=[#VVS# "FBC" "0, 171, 255, 255" #@#Style.inc]#MTAJR1##Coup21#

[E2001]
Meter=Image
MeterStyle=C2001|STPC
LeftMouseUpAction=[#VVS# "FBC" "0,128,192" #@#Style.inc]#MTAJR1##Coup22#

[E2101]
Meter=Image
MeterStyle=C2101|STPC
LeftMouseUpAction=[#VVS# "FBC" "0,128,0" #@#Style.inc]#MTAJR1##Coup23#

[E2200]
Meter=Image
MeterStyle=C2200|STPC
LeftMouseUpAction=[#VVS# "FBC" "0,0,255" #@#Style.inc]#MTAJR1##Coup24#

[E8230]
Meter=Image
MeterStyle=C230|STPC
LeftMouseUpAction=[#VVS# "FBC" "0,0,0" #@#Style.inc]#MTAJR1##Coup25#

[E8235]
Meter=Image
MeterStyle=T230|STPC
LeftMouseUpAction=[#VVS# "FBC" "60,60,60" #@#Style.inc]#MTAJR1##Coup26#

[T3121]
Meter=Image
MeterStyle=T121|STPC
X=117
Y=15r
LeftMouseUpAction=[#VVS# "FBC" "225,225,225" #@#Style.inc]#MTAJR1##Coup27#

[V2230]
Meter=Image
MeterStyle=V230|STPC
LeftMouseUpAction=[#VVS# "FBC" "102,131,144" #@#Style.inc]#MTAJR1##Coup28#

[V2240]
Meter=Image
MeterStyle=V240|STPC
LeftMouseUpAction=[#VVS# "FBC" "208,52,56" #@#Style.inc]#MTAJR1##Coup29#

[V2250]
Meter=Image
MeterStyle=V250|STPC
LeftMouseUpAction=[#VVS# "FBC" "253,108,63" #@#Style.inc]#MTAJR1##Coup30#

[V2260]
Meter=Image
MeterStyle=V260|STPC
LeftMouseUpAction=[#VVS# "FBC" "249,78,124" #@#Style.inc]#MTAJR1##Coup31#

[V2270]
Meter=Image
MeterStyle=V270|STPC
LeftMouseUpAction=[#VVS# "FBC" "164,52,99" #@#Style.inc]#MTAJR1##Coup32#

[V2280]
Meter=Image
MeterStyle=V280|STPC
LeftMouseUpAction=[#VVS# "FBC" "219,179,40" #@#Style.inc]#MTAJR1##Coup33#

[V2290]
Meter=Image
MeterStyle=V290|STPC
LeftMouseUpAction=[#VVS# "FBC" "161,197,4" #@#Style.inc]#MTAJR1##Coup34#

[V2300]
Meter=Image
MeterStyle=V300|STPC
LeftMouseUpAction=[#VVS# "FBC" "33,115,70" #@#Style.inc]#MTAJR1##Coup35#

[V2310]
Meter=Image
MeterStyle=V310|STPC
LeftMouseUpAction=[#VVS# "FBC" "47,210,6" #@#Style.inc]#MTAJR1##Coup36#

[V2320]
Meter=Image
MeterStyle=V320|STPC
LeftMouseUpAction=[#VVS# "FBC" "3,208,252" #@#Style.inc]#MTAJR1##Coup37#

[V2330]
Meter=Image
MeterStyle=V330|STPC
SolidColor=52,92,252
LeftMouseUpAction=[#VVS# "FBC" "52,92,252" #@#Style.inc]#MTAJR1##Coup38#

[V2340]
Meter=Image
MeterStyle=V340|STPC
LeftMouseUpAction=[#VVS# "FBC" "57,64,197" #@#Style.inc]#MTAJR1##Coup39#