[Variables]

;HDD
OD=Öffnen Sie die Disc!
U=Gebraucht 
F=kostenlos 
U1=Zugriff
RE=Lesungen
WR=Schreiben
IT=Subject
LCRB=Linksklick öffnet den Müll
LCERB=Rechts klicken leer in den Papierkorb
LCADD=Linksklick Uhren die Details. Linksklick zu verstecken
TOTA=Total
RecBin=Trash
REA=L
WRA=S
REAT=Kumulative Lesungen
WRAT=kumulative Schriften
Name=Name
PTRCP=Verwenden des Papierkorbs  
DSTM=Rate
NDFC=Anzahl der Dateien
TDFC=Dateigröße
Vide=Leer
Paso=Keine Objekte
HDDAC1=Aktivität

;CPU
CPU=CPU verwendet
ID=Ungenutzte
CPS=CPU-Geschwindigkeit
MHz=MHz
CP=CPU
TEMPE=Temperatur
CPName=Prozessor Name
BUSP=Systembus
Mulr=Multiplier

;GPU
FSPD=Fan
GPUSD=GPU Geschwindigkeit
MemSD=Memory Clock
Memgu=Benutzter Speicher
Horlo=Clock
Memor=Memory
T33P1=GPU Geschwindigkeit
T35P1=Geschwindigkeit
T36P1=Speichergeschwindigkeit
T38P1=Speichergröße
GPU=GPU
MSIAFB=Benötigt MSIAfterBurner

;RAM & SWAP
OTM=Öffnen den Task-Manager
RAU=Ram verwendet 
SWU=Swap verwendet 
RA=RAM
SW=SWAP
RAF=Ram kostenlos
SWF=Swap kostenlos
TOMEMO=Gesamtspeicher

;Players
STP=Song Position
POS=Position
P&P=Pause & Play
ST=Stopp
PRE=Zurück
NEXt=Weiter
PRG=Fortschritt
PLAY=Wiedergabe
DURA=Dauer
Playr=Spieler
AlYe=Album - Jahr
PDIFO1=Keine Angabe

;Volume
MU=Mute
VOL=Volumen
VOLU=Volume up
VOLD=Volume down
VOS=Volume mixer
CPA=Konfigurieren Sie Audiogeräte
SS50=Stellen Sie den Ton
NXDVE=Nächstes Gerät
VOLC=Linksklick um den Ton zu erhöhen. Rechtsklick für reduzierte
NXDV1=Audio device
DR1=Rechts
GA1=Link

;Processes
PRO=Prozess
TPP=Top Prozess
RRM1=Ressourcen monitor
RRM2=Ressourcen, die von Rainmeter

;Net
LI=Local IP
IN=In
OUT=Out
NT=Netto
NTW=Netzwerk
WI=Wifi
Dowl=Empfang
Upld=Emission 
Adapter=Adapter
DNSA=DNS-Adresse
Gaway=Gateway
RESSTA=Rechtsklick auf die Statistiken zurücksetzen
WIUPD=Linksklick, ein Update
Wifi1=Broadcast name
Wifi2=Encryption
Wifi3=Supported band
RCOGO=Rechtsklick öffnet www.google.com
LCOS=Linksklick öffnet Suche

;Gmail
NGM1=Neue E-Mail
NGM2=Keine neuen E-Mail
NGM3=Konto
NGM4=Neue E-Mails
T19P1=GMail User
T20P1=Benutzername 
T21P1=Passwort

;Weather
WEATH=Wetter
RCOY1=Open "weather.codes"
SWE=Vereinfachtes Wetter
Dem3=Heute
Dem1=Morgen
High=High
Low=Low
T15P1=Code Wetter
T16P1=Suchen Sie Ihr Code auf "weather.codes"
T17P1=Einheit
T18P1=Temperatureinheit..#CRLF#m für Celsius oder Fahrenheit für f
jpw="Sunday":"Sonntag","Monday":"Montag","Tuesday":"Dienstag","Wednesday":"Mittwoch","Thursday":"Donnerstag","Friday":"Freitag","Saturday":"Samstag"
jpw1="Jan":"Jan","Feb":"Feb","Mar":"Mär","Apr":"Apr","Jun":"Jun","Jul":"Jul","Aug":"Aug","Sep":"Sep","Oct":"Okt","Nov":"Nov","Dec":"Dez"
Sunrise=Sunrise
Sunset=Sunset
Humidi=Feuchtigkeit
Current=Strom
Preci1=Regen
Feel1=Filz
Moon=Mond
Wind=Wind
Pressure=Druck

;CtrShut
HIBe=Standby
RESt=Neustart
REST1=Erweiterte Neustart
SHUt=Ausschalten
LOGo=Disconnect
Shutau1=Schalten Sie Ihren PC nach
Shutau2=Linksklick startet den Countdown. Rechtsklick bricht die Aktion
Shutau3=Neustart nach
LOCWK=Lock-Station

;Calendar
Mo=Mo
Tu=Di
We=Mi
Th=Do
Fr=Fr
Sa=Sa
Su=So
SUND=Sonntag
MOND=Montag
TUES=Dienstag
WEDN=Mittwoch
THUR=Donnerstag
FRID=Freitag
SATU=Samstag
Week=Woche
Week+=Woche
Calend=Kalender
January=Januar
February=Februar
March=März
April=April
May=Mai
June=Juni
July=Juli
August=Augustus
September=September
October=Oktober
November=November
December=Dezember
Sun=Son
Mon=Mon
Tue=Die
Wed=Mit
Thu=Don
Fri=Fre
Sat=Sam
Jan=Jan
Feb=Feb
Mar=Mär
May=Mai
Apr=Apr
Jun=Jun
Jul=Jul
Aug=Aug
Sep=Sep
Oct=Okt
Nov=Nov
Dec=Dez
CFANT=Klicken Sie auf eine Notiz zu öffnen
J=T
W=W
JDLA=Tag des Jahres
Sur=On
SC+=W
CF12=Linksklick aktiviert die Ereignisanzeige. Rechtsklick zu verstecken
CF1C=Hide Ereignis (Linksklick)#CRLF#Rechtsklick zeigt Ereignisse
CF2C=Linksklick zeigt den folgenden Monat
CF2C1=Linksklick zeigt den folgenden Monat#CRLF#Rechts Klick ändert sich das Aussehen des Ereignisanzeige
CF3C=Linksklick  zeigt den vorherigen Monat#CRLF#Rechts Klick ändert sich das Aussehen des Indikators des Tages
CF4C=Zurück zum aktuellen Monat
CF5C=Linksklick öffnet die Datei von Ereignissen
CF9C=Klicken Sie auf die Datei von Ereignissen zu öffnen
CF10C=Linksklick ein- / ausblenden der Monat (Ereignisdateien)
SHEV=Linksklick ein- / ausblenden die Ereignisse #CRLF#Rechts Klick ändert sich das Aussehen der Note Indikator

;Clock, Date, Time, Worldtime
D&T=Datum & Uhrzeit
D&THP=Panel-Datum und Uhrzeit
UP=Mehr
TOTW=Zeit weltweit
CTTD=control.exe timedate.cpl
Day=Tag
Date=Datum
MTH=Monat
Year=Jahr
UPT=Zeit Sitzung
UPT1=Dauer
Time=Zeit
TZNE=Zeitzone
Day1=Tag
hour=Zeit
minutes=Minuten
secondes=Sekunden
D=t

;Note, Folder, Picture, Wallpaper
OFD=Verzeichnis öffnen
OMP=Verzeichnis von Videos
MOVI=Filme
OMSP=Verzeichnis der Musik
MUSI=Music
OPP=Verzeichnis der Abbildungen
PICTU=Bilder
OPDO=Verzeichnis der Dokumente
Docum=Dokumente
OPDOw=Verzeichnis von Downloads

;Slideshow
KLCP=Halten Linksklick für eine Vorschau
Siz=Größe
StSli=Stop und Neustarten der Diashow.
SALPP=Installieren als Hintergrund
SBOF=Diashow Vollbild und Diashow Tapete
COCP=Klicken Sie auf das Bild zu ändern
SGRIS=Graue Tönung
AUTGS=Aufbringen einer grauen Farbton
PSSKAS=Keep the proportions
Ratio=Proportions
PEFS1=Vollbild
SLIINFO=Übergangseffekte für Diashows

;Various
SYS=System
LCOP=Linksklick öffnet sich das Menü. Rechtsklick schließt das Menü.
TOL=Werkzeuge
ADTS=Administration Tools
STS=Systemtools
DTOS=Andere Werkzeuge
WCalc=Rechner
WLD=Willkommen
YACS=Sie sind angemeldet von
YPHD=Der Name Ihrer HDD
UTSI=Der gesamte Speicherplatz ist
HIUA=Es verwendet
HFSIA=Der freie Raum ist
T1P22=Linksklick öffnet sich das Dock. Rechtsklick auf den Bauernhof
HIDE=Ausblenden
SHOW=Anzeigen
BOOK=Favoriten
ALPS=Alle Programme
Run=Start
CBD1=Sie verwenden
CBD2=Es ist
CBD3=Verbunden aus
TPE1=Display-Größe
Uptuc=Update Alle
O/F=Ein / Aus
Pour=zu
Valrs=Die Werte für die

;Battery
BAP=Batterie
BAPF=Gefüllt Batterie
OPOP=Öffnen Sie die Energieoptionen
BAPF1=Sector
BAT1=Keine Batterie
BAT2=Laden
BAT3=Critical!
BAT4=Low
BAT5=Gefüllt 
BAT6=Verbleibende

;User
User=Benutzer
USFold=Aufzeichnungen
OUP=Profil Öffnen
PN=Name of the PC
MOD=Modell
MAN=Hersteller
PR=Produkt
OS=OS
INF=Information
Games=Spiele (Backups)
Bureau=Office
RMUF=Ordner Rainmeter
CMB=Motherboard

;Presentation
T1P1=Suite-Konfiguration.
T3P1=Viewer-Verzeichnis
MIAS=Übergangszeit
T6P1=Übergangszeit zwischen den einzelnen Bild.
T7P1=Lage der videos
T9P1=Lage der Musik
T11P1=Lage der Bild
T13P1=Spieler
T14P1=Geben Sie den Namen Ihres Players. Wählen Sie zwischen Ihrem Player Winamp, AIMP, MusicBee, Mediamonkey, WMP, VLC...

;Options
CLO=close
T3P10=Wählen
CPMAJ=Update
REFALL=Alle skins Aktualisieren
Fondconf1=Klicken Sie anwenden
CF11C=Rechtsklick zu aktualisieren
T3P9=Linksklick öffnet sich das Menü. Rechtsklick schließt das Menü.
CF6C=Linksklick anzeigen / verbergen
STCCMAJ=Ändern Sie die Verknüpfungen
T8P5=Ändern Sie das Symbol
T9P6=Bild ändern
T5P8=Ändern Sie den Namen
T6P8=Wechsel Informationen
OACT=Aktuelle Option
Oui=Ja
Non=Nein

;Configuration
T2P9=Farbe
T4P9=Ausgewählte Farbe
CDPDM=Aktuelle Farbe
T11P9=Anderes Farbwahlen mit#CRLF#Farbspektrum von Kaelri
T2P10=Font
Op1=Nein
Op2=Shadow
Op3=Border
Op4=Option für Schriftarten
Op8=Wirkung
Op11=Option for text style
Op13=Bold
Op15=Kursiv
Op16=Klicken Sie konfigurieren
T3P16=Transparency
MTHes=Thema anwenden
MTHes2=Effekt anwenden
T1PEFB1=Deaktiviert die Wirkung
T1PEFB3=Deaktiviert die Themen
T1PEFB2=Klicken Sie auf einen Effekt zu aktivieren
T1P23=Auswahleffekt
T2P23=Visuelle Effekt für Themen.
DOTET=Effect "Dot"
ACEFFDOT=Aktivieren dots
DSEFFDOT=Deaktivieren dots
Select=Auswahl
ACSELC=Selektionseffekt aktivieren
DESELC=Deaktivieren Selektionseffekt
CPCLC=Klicken Sie auf die ausgewählte Farbe anzuwenden
SPHY1=Farbe verwendet für Kalender (Tage vor und nach Monat)
T5P5=Die Anwendung ändern und den Namen.#CRLF#das neue Symbol Dann wählen.
T5P6=Klicken Sie hier, um den Anwendungspfad zu ändern.#CRLF#Ändern Sie dann den Namen (falls erforderlich) auf diesem Bedienfeld.
T5P7=Verwenden Sie den doppelten linken Klick auf "Reisen" zwischen Festplatten und Ordnern.
T0P0=Wählen Sie das Verzeichnis mit der rechten Maustaste.
T0P1=Klicken Sie auf "Appl1", um die Einstellungen der ersten Anwendung zu ändern.
T0P2=Klicken Sie mit der rechten Maustaste, um Anwendungen auszuwählen (aktuelle Namen und Symbole).
T0P3=Wiederholen Sie das gleiche für die anderen (klicken Sie auf "Appl2" ...).
T6P5=Standorte

;Evènements
Valen=Valentine
14J=Fête Nationale (French)
Hawe=Halloween
TSNT=Toussaint
JDLAN=Jahres Tages
25de=Weihnachten
FDTF=Labor Day
2FEV=Chandeleur
1MRS=Große Muttertag
8MRS=Sieg-Tag 1945
17Mp=St. Patrick
14Ma=Ascension
24ma=Pfingsten
Printemps=Feder
Avril1=1. April :-).
FDmere=Muttertag
21ju=Vatertag - Sommer
15Ao=Annahme
Summer=Sommer
11Nov=1918 Armistice
21de=Schnee
23seb=Fall