[Variables]
; HDD
OD=Abre el disco duro
U=Uso
U1=Acceso
F=Sobra
RE=Lectura
WR=Escritura
IT=archivo(s)
LCRB=Pulse el botón izquierdo para abrir la papelera
LCERB=click derecho vaciar la papelera
LCADD=click izquierdo para mostrar detalles ./ Ocultar con click drecho
TOTA=Total
RecBin=Papelera
REA=L
WRA=E
REAT=Lecturas acumuladas
WRAT=Escrituras acumuladas
Name=Nombre
PTRCP=Uso de la papelera
DSTM=Porcentaje del relleno
NDFC=Número de archivos
TDFC=Tamaño de archivos
Vide=Vacío
Paso=No hay archivos
HDDAC1=Actividad

; CPU
CPU=uso del CPU
ID=no utilizado
CPS=Velocidad de la CPU
MHz=MHz
CP=CPU
TEMPE=Temperatura
CPNAME=Nombre del procesador
BUSP=Bus de sistema
Mulr=Multiplicadores

; GPU
FSPD=Ventilador
GPUSD=Velocidad de la GPU
MemSD=Memoria del reloj
Memgu=Memoria utilizada
Horlo=Reloj
Memor=Memoria
T33P1=Velocidad de la GPU
T35P1=Velocidad
T36P1= Velocidad de la memoria
T38P1=Tamaño de la memoria
GPU=GPU
MSIAFB=Requiere MSIAfterBurner

; RAM y SWAP
OTM= Abrir el Administrador de tareas
RAU=Udo de la memoria RAM
SWU=Uso de la memoria virtual SWAP
RA=Ram
SW=Swap
RAF=RAM sobrante
SWF=Swap sobrante
TOMEMO=Memoria total

;Players
STP=Posición de la canción
POS=Posición
P&P=Pausar y Reanudar
ST=Detener
PRE=Anterior
Next=Siguiente
PRG=Progreso
PLAY=Replroducir
DURA=Duración
Playr=Reproductor
Alye=Álbum - Año
PDIFO1=No hay información

;Volumen
MU=Silencio
VOL=Volumen
VOLU=Aumentar el volumen
VOLD=Bajar volumen
VOS=Volumen de mezclador
CPA=Configurar los dispositivos de salida de audio
SS50=Ajuste el sonido
NXDVE=Siguiente Dispositivo
VOLC=Click izquierdo para aumentar el volumen. click derecho para reducir el volumen.
NXDV1=Dispositivo de audio
DR1=Derecha
GA1=Izquierda

; Proceso
PRO=Procesos
TPP=proceso mayor
RRM1=Monitor de recursos
RRM2=Recursos utsados por Rainmeter

; Net
LI=IP local
IN=entrada
OUT=salida
NT=Net
NTW=internet
Wi=Wifi
Dowl=Descarga
UPLd=Subida
Adapter=Adaptador
DNSA=Direccion DNS
Gaway=puerta
RESSTA=click derecho para restablecer las estadisticas.
WIUPD=Click izquierdo para actualizar.
Wifi1=Proveedor
Wifi2=Cifrado
Wifi3=Tipo (estándar)
RCOGO=click derecho para abrir www.google.com
LCOS=click izquierdo para realizar alguna búsqueda

; Gmail
NGM1=Nuevos correos electrónicos
NGM2=No hay correos nuevos.
NGM3=Cuenta
NGM4=nuevos mensajes
T19P1=Usuario de Gmail
T20P1=Nombre de usuario
T21P1=Contraseña

; El Tiempo
Weath=Tiempo
RCOY1=Abrir "weather.codes"
SWE=Tiempo resumido
dem3=Hoy
dem1=Mañana
High=Alta
Low=Baja
T15P1=Código tiempo
T16P1=Busca tu código del clima en weather.codes
T17P1=Unidad
T18P1=Unidad de temperatura.#CRLF# m para Celsius - f para Fahrenheits
jpw = "Sunday": "Domingo", "Monday": "Lunes", "Tuesday": "Martes", "Wednesday": "Miercoles", "Thursday": "Jueves", "Friday": "Viernes" "Saturday": "Sabado"
jpw1="Jan":"Ene","Feb":"Feb","Mar":"Mar","Apr":"Abr","May":"May","Jun":"Jun","Jul":"Jul","Aug":"Ago","Sep":"Sep","Oct":"Oct","Nov":"Nov","Dec":"Dic"
Sunrise=Salida del sol
Sunset=Puesta del sol
Humidi=Humedad
Current=Corriente
Preci1=Lluvia
Feel1=Filtro
Moon=Luna
Wind=Viento
Pressure=Presión

; CtrShut
HIBE=Espera
REST=Reiniciar
REST1=Reiniciar avanzada
SHUt=Apagar
LOGO=Desconectar
Shutau1=Apagar el PC tras
Shutau2=Pulse el click izquierdo pone en marcha la cuenta atrás. Haz clic derecho para cancelar la acción
Shutau3=Reiniciar después
LOCWK=Bloquear la estacion

;Calendar
Mo=Lu
Tu=Ma
We=Mi
Th=Ju
Fr=Vi
Sa=Sa
Su=Do
SUND=Domingo
MOND=Lunes
TUES=Martes
WEDN=Miercoles
THUR=Jueves
FRID=Viernes
SATU=Sabado
Week=Semana
Week+=Semana
Calend=Calendar
January=Enero
February=Febrero
March=Marzo
April=Abril
May=Mayo
June=Junio
July=Julio
August=Agosto
September=Septiembre
October=Octubre
November=Noviembre
December=Diciembre
Sun=Dom
Mon=Lun
Tue=Mar
Wed=Mier
Thu=Juev
Fri=Vier
Sat=Sab
Jan=Ene
Feb=Feb
Mar=Mar
Apr=Abr
May=May
Jun=Jun
Jul=Jul
Aug=Ago
Sep=Sep
Oct=Oct
Nov=Nov
Dec=Dic
CFANT=Haga clic para abrir una nota
J=D
W=S
JDLA=Día del año
Sur=Of
SC+=W
CF12=Pulse el botón izquierdo par activar el indicador de evento. Haga clic derecho para apagarlo.
CF1C=Pulse el botón izquierdo para ocultar los eventos #CRLF# Clic derecho para mostrar los eventos
CF2C=Pulse el botón izquierdo para mostrar el mes siguiente
CF2C1=Pulse el botón izquierdo para mostrar el mes siguiente #CRLF# Haz clic derecho par cambiar el aspecto del indicador de evento
CF3C=Pulse el botón izquierdo para mostrar el mes anterior #CRLF# Haz clic derecho para cambiar el aspecto del indicador del día
CF4C=Volver al mes actual
CF5C=click izquierdo para abrir el archivo de eventos.
CF9C=Haga clic para abrir el archivo de eventos
CF10C=Pulse el botón izquierdo para mostrar / oculta los archivos de eventos
VEHC=click izquierdo para  Mostrar / ocultar los eventos #CRLF# Clic derecho para cambiar el aspecto del indicador de la nota.

;Clock, Date, Time, Worldtime
D&T=Fecha y hora
D&THP=Fecha y hora del panel
UP=Más
TOTW=Tiempo en todo el mundo
CTTD=control.exe timedate.cpl
Day=Día
Date=Fecha
MTH=Mes
Year=año
UPT=Tiempo de sesión
UPT1=Tiempo
Time=Hora
;Time=Tiempo de vida
TZNE=Tiempo de la zona
Day1=Día(s)
hour=Hora(s)
minutes=minutos
secondes=segundos
D=d

;Note, Folder, Picture, Wallpaper
OFD=Abrir Directorio 
OMP=Carpeta de videos 
MOVI=videos 
OMSP=carpetas de musica
MUSI=Musica
OPP=carpetas de imagenes
Pictu=Imagenes
OPDO=carpetas de documentos
Docu=Documentos
OPDOw=carpeta de descargas
 
;Slideshow
KLCP=click izquierdo para una vista previa
Siz=Tamaño
StSli=Detener y reiniciar la presentación de diapositivas.
SALPP=Instalar como fondo de pantalla
SBOF=Presentación de diapositivas en pantalla completa y fondos de escritorio
COCP=Haga clic para cambiar de imagen
SGRIS=Tinte gris
AUTGS=Aplica un tono gris.
PSSKAS=Proporciones
Ratio=Radio
PEFS1=Pantalla completa
SLIINFO=Transición para presentaciones de diapositivas

;Divers
SYS=Sistema
LCOP=click izquierdo par abrir el menú. Haz clic derecho para cerrar el menú.
TOL=Herramientas
ADTS=Herramientas de administración
STS=Herramientas del sistema
DTOS=Otras herramientas
Wcalc=Calculadora
WLD=Bienvenido
YAC=Tu estas en el sistema de
YPHD=el nombre de tu disco duro
UTSI=el espacio total es
HIUA=Utilizado
HFSIA=el Espacio libre es
T1P22=Click izuierdo para abrir el muelle.Click drecho para cerrar
HIDE=Ocultar
SHOW=Mostrar
BOOK=Favoritos
ALPs=Todos los programas
Run=Ejecutar
CDB1=Utilizar
CBD2=esto es 
CBD3=conectado desde
TPE1=Tamaño de la pantalla
Uptuc=Actualizar todo
O/F=Prender  / Apagar
Pour=para
ValRS=Los valores para 

;Battery
BAP=Bateria
BAPF=Bateria completa
KOMET=Abrir las Opciones de energía
BAPF1=Sector
BAT1=Sin batería
BAT2=carga
BAT3=Crítico!
BAT4=Bajo
BAT5=llena
BAT6=Restante

;User
User=Usuario
USFold=Carpetas
OUP=Abrir perfil del Usuario
PN=Nombre de la PC
MOD=Modelo
MAN=Fabricante
PR=Producto
OS=Sistema Operativo
INF=Información
Games=Juegos (copias de seguridad)
Bureau=Oficina
RMUF=Carpeta de Rainmeter
CMB=Placa Base

;Presentation
T1P1=Configuración de la suite.
T3P1=Directorio del Slideshow
MIAS=Transición
T6P1=Tiempo de transición entre cada imagen.
T7P1=Ubicación de la carpeta vídeos 
T9P1=Ubicación de la carpeta música
T11P1=Ubicación de la carpeta imagenes 
T13P1=Reproductor
T14P1=Introduzca el nombre del reproductor que usa. Elige tu reproductor entre esta lista: Winamp, AIMP, MusicBee, MediaMonkey, WMP, VLC ...

;Options
CLO=cerrar
T3P10=Seleccionar
CPMAJ=Actualizar
REFALL=Actualizar todas las pieles.
Fondconf1=Haga clic para aplicar
CF11C=Haga clic para actualizar
T3P9=Click izquierdo para abrir el menú. click derecho para cerrar el menú.
CF6C=Pulse el botón izquierdo para mostrar / disimular
STCCMAJ=Cambiar los accesos directos
T8P5=Cambiar el icono
T9P6=Cambiar la imagen
T5P8=Cambiar el nombre
T6P8=Cambiar la información 
OACT=Opción actualmente escogida
Oui=Sí
Non=No

;Configuration
T2P9=Color
T4P9=Color seleccionado
CDPDM=Color actual
T11P9=Otras opciones de color #CRLF# Color del visualizador(Spectrum) de Kaelri
T2P10=Tipo de letra
OP1=Ninguno
OP2=Sombra
OP3=Borde
op4=Opción para el tipo de letras.
op8=Efecto
OP11=Opción para el estilo de texto
OP13=Negrita
OP15=Cursiva
OP16=Haga clic para configurar
T3P16=Transparencia
MTHes=Aplicar tema
MTHes2=Aplicar efecto
T1PEFB1=Desactiva efecto
T1PEFB3=Desactiva los temas
T1PEFB2=Haga clic en un efecto para activarlo.
T1P23=Seleccion de efectos
T2P23=Efecto visual para los temas.
DOTET=Efecto "Dot"
ACEFFDOT=Habilitar dots
DSEFFDOT=Desactivar dots
Select=Seleccionar
ACSELC=Habilitar selección de efectos
DESELC=Desactivar seleccion de efectos
CPCLC=Haga clic para aplicar el color seleccionado
SPHY1=Color que se utiliza para los calendarios (días anteriores y posteriores a mes)
T5P5=Cambiar la aplicación y el nombre. #CRLF# A continuación, seleccione el icono de nuevo.
T5P6=Haga clic aquí para cambiar la ruta de las aplicaciones.#CRLF#A continuación, cambie el nombre (si es necesario) en este panel.
T5P7=Utilice el doble clic izquierdo para "viajar" entre discos y carpetas.
T0P0=Seleccione el directorio con el botón derecho del ratón.
T0P1=Haga clic en "Appl1" para cambiar la configuración de la primera aplicación.
T0P2=Haga clic derecho para seleccionar las aplicaciones (nombres e iconos actuales).
T0P3=Repita lo mismo para los demás (haga clic en "Appl2" ...).
T6P5=Ubicaciones

Eventos;
Valen=Dia de San Valentin
14J=Fête Nationale (French) 
Hawe=de Halloween
TSNT=Toussaint *
JDLAN=Día de Año Nuevo
25del=Navidad
FDTF=Día del Trabajo
2FEV=Chandeleur*
1MRS=Día de la abuela
8MRS=Día de la Victoria 1945
17Mp=San Patricio
14mA=Ascensión 
24mA= Pentecostés
Printemps=Primavera
Avril1=primero de abril
FDmere=Día de la Madre
21ju=Día del Padre - Verano
15Ao=Asunción
Summer=Verano 
11Nov=Armisticio de 1918
21de=Invierno
23seb=Otoño