[Variables]


;################################################################################################################################################################################
;MASKS===========================================================================================================================================================================
;################################################################################################################################################################################

MASK_USR_PIC=#@#Images\Environment\mask_pic_usr.png
MASK_MEDIA_COVER=#@#Images\Environment\mask_cover_media.png



;################################################################################################################################################################################
;OTHERS==========================================================================================================================================================================
;################################################################################################################################################################################

HELP_AL1=#@#Images\Launcher_Conf\help_al1.png
HELP_AL2=#@#Images\Launcher_Conf\help_al2.png
HELP_AL3=#@#Images\Launcher_Conf\help_al3.png
HELP_LL1=#@#Images\Launcher_Conf\help_ll1.png
HELP_LL2=#@#Images\Launcher_Conf\help_ll2.png

WALLPAPER=#@#Images\wallpaper.jpg

Folder_Icon=#@#Images\Settings\icon_folder.png

;################################################################################################################################################################################
;BORDERS=========================================================================================================================================================================
;################################################################################################################################################################################

Bor_TM_Main=#@#Images\Main\border_top_menu.png
Bor_TM_Environment=#@#Images\Environment\border_top_menu.png
Bor_TM_Internals=#@#Images\Internals\border_top_menu.png
Bor_TM_Settings=#@#Images\Settings\border_top_menu.png
Bor_TM_Storage=#@#Images\Storage\border_top_menu.png
Bor_TM_Launcher_Conf=#@#Images\Launcher_Conf\border_top_menu.png

Bor_Main_MA=#@#Images\Main\border_ma1.png
Bor_Main_SE=#@#Images\Main\border_se.png
Bor_Main_File=#@#Images\Main\File\border_file.png

Bor_L=#@#Images\Main\border_launcher.png
Bor_L_SL=#@#Images\Main\sl_border.png
Bor_L_AL=#@#Images\Main\al_border.png
Bor_L_LL=#@#Images\Main\ll_border.png

Bor_Env_Media=#@#Images\Environment\border_media.png
Bor_Env_News=#@#Images\Environment\border_news.png
Bor_Env_Steam=#@#Images\Environment\border_steam.png
Bor_Env_Time=#@#Images\Environment\border_time.png
Bor_Env_USR=#@#Images\Environment\border_usr.png
Bor_Env_Weather=#@#Images\Environment\border_weather.png
Bor_Env_WorldMap=#@#Images\Environment\border_worldmap.png

Bor_Int_CPU=#@#Images\Internals\border_cpu.png
Bor_Int_CPU_Rounds=#@#Images\Internals\border_rounds_cpu.png
Bor_Int_CPU_Cores=#@#Images\Internals\border_cores_cpu.png
Bor_Int_CPU_USAGE=#@#Images\Internals\border_graph_usage_cpu.png
Bor_Int_GPU=#@#Images\Internals\border_gpu.png
Bor_Int_GPU_Graph=#@#Images\Internals\border_graph_gpu.png
Bor_Int_GPU_Hex=#@#Images\Internals\border_hex_gpu.png
Bor_Int_MB=#@#Images\Internals\border_mb.png
Bor_Int_MB_Fan=#@#Images\Internals\border_fanspeed_mb.png
Bor_Int_NW=#@#Images\Internals\border_nw.png
Bor_Int_NW_Graph=#@#Images\Internals\border_graph_nw.png
Bor_Int_NW_UL=#@#Images\Internals\border_ul_nw.png
Bor_Int_NW_DL=#@#Images\Internals\border_dl_nw.png
Bor_Int_PRO=#@#Images\Internals\border_pro.png
Bor_Int_RAM=#@#Images\Internals\border_ram.png
Bor_Int_RAM_Graph=#@#Images\Internals\border_graph_ram.png
Bor_Int_RAM_Bar=#@#Images\Internals\border_bar_ram.png
Bor_Int_SWAP_Bar=#@#Images\Internals\border_bar_swap.png

Bor_LC_AL=#@#Images\Launcher_Conf\border_al.png
Bor_LC_LL=#@#Images\Launcher_Conf\border_ll.png

Bor_OV=#@#Images\Overview\border_ov.png

Bor_SET_Launcher=#@#Images\Settings\border_launcher.png
Bor_SET_Player=#@#Images\Settings\border_player.png
Bor_SET_RSS=#@#Images\Settings\border_rss.png
Bor_SET_SlideShow=#@#Images\Settings\border_slideshow.png
Bor_SET_SpeedFan=#@#Images\Settings\border_speedfan.png
Bor_SET_Storage=#@#Images\Settings\border_storage.png
Bor_SET_User=#@#Images\Settings\border_user.png
Bor_SET_Weather=#@#Images\Settings\border_weather.png

Bor_ST_HDD=#@#Images\Storage\border_hdd.png
Bor_ST_USB=#@#Images\Storage\border_usb.png
Bor_ST_NET=#@#Images\Storage\border_net.png
Bor_ST_ODD=#@#Images\Storage\border_odd.png
Bor_ST_TitleHDD=#@#Images\Storage\border_title_hdd.png
Bor_ST_TitleUSB=#@#Images\Storage\border_title_usb.png
Bor_ST_TitleNET=#@#Images\Storage\border_title_net.png
Bor_ST_TitleODD=#@#Images\Storage\border_title_odd.png




;################################################################################################################################################################################
;BACKGROUNDS=====================================================================================================================================================================
;################################################################################################################################################################################

BG_CAL=#@#Images\Environment\bg_cal_time.png
BG_MEDIA_Cover=#@#Images\Environment\bg_cover_media.png
BG_MEDIA_BAR=#@#Images\Environment\bg_bar_media.png
BG_WEATHER=#@#Images\Environment\bg_details_weather.png
BG_WEATHER_SUN=#@#Images\Environment\bg_sun_weather.png
BG_NEWS=#@#Images\Environment\bg_feeds_news.png
BG_STEAM=#@#Images\Environment\bg_news_steam.png
BG_NOTES=#@#Images\Environment\bg_notes_usr.png
BG_USR_PIC=#@#Images\Environment\bg_pic_usr.png

BG_WORLDMAP=#@#Images\Environment\bg_worldmap.png

BG_LOCK=#@#Images\Lock\bg_lock.png

BG_FILE=#@#Images\Main\File\bg_file.png

BG_RECYCLE_STATUS=#@#Images\Overview\bg_recycle_status.png





;################################################################################################################################################################################
;BUTTONS=========================================================================================================================================================================
;################################################################################################################################################################################

BTN_ARR_LEFT=#@#Images\Buttons\btn_arr_l.png
BTN_ARR_LEFT_HOVER=#@#Images\Buttons\btn_arr_l_hover.png
BTN_ARR_RIGHT=#@#Images\Buttons\btn_arr_r.png
BTN_ARR_RIGHT_HOVER=#@#Images\Buttons\btn_arr_r_hover.png

BTN_DBL=#@#Images\Buttons\btn_dbl.png
BTN_DBL_HOVER=#@#Images\Buttons\btn_dbl_hover.png

BTN_L_R1=#@#Images\Buttons\btn_l_r1.png
BTN_L_R2=#@#Images\Buttons\btn_l_r2.png
BTN_L_R3=#@#Images\Buttons\btn_l_r3.png
BTN_L_R4=#@#Images\Buttons\btn_l_r4.png
BTN_L_R5=#@#Images\Buttons\btn_l_r5.png

BTN_NUM=#@#Images\Buttons\btn_num.png

BTN_OPEN=#@#Images\Buttons\btn_open.png
BTN_OPEN_HOVER=#@#Images\Buttons\btn_open_hover.png

BTN_OU=#@#Images\Buttons\btn_ou.png
BTN_OU_HOVER=#@#Images\Buttons\btn_ou_hover.png

BTN_RC_BIG=#@#Images\Buttons\btn_rc_big.png
BTN_RC_BIG_HOVER=#@#Images\Buttons\btn_rc_big_hover.png
BTN_RC_SMALL=#@#Images\Buttons\btn_rc_small.png

BTN_RE_BLUE=#@#Images\Buttons\btn_re_b.png
BTN_RE_BLUE_HOVER=#@#Images\Buttons\btn_re_b_hover.png
BTN_RE_GREEN=#@#Images\Buttons\btn_re_gr.png
BTN_RE_GREEN_HOVER=#@#Images\Buttons\btn_re_gr_hover.png
BTN_RE_RED=#@#Images\Buttons\btn_re_r.png
BTN_RE_RED_HOVER=#@#Images\Buttons\btn_re_r_hover.png
BTN_RE_WHITE=#@#Images\Buttons\btn_re_w.png
BTN_RE_WHITE_HOVER=#@#Images\Buttons\btn_re_w_hover.png

BTN_REC_BLUE=#@#Images\Buttons\btn_rec_b.png
BTN_REC_BLUE_HOVER=#@#Images\Buttons\btn_rec_b_hover.png
BTN_REC_RED=#@#Images\Buttons\btn_rec_r.png
BTN_REC_RED_HOVER=#@#Images\Buttons\btn_rec_r_hover.png
BTN_REC_BLUE_SMALL=#@#Images\Buttons\btn_rec_b_small.png
BTN_REC_BLUE_SMALL_HOVER=#@#Images\Buttons\btn_rec_b_small_hover.png
BTN_REC_RED_SMALL=#@#Images\Buttons\btn_rec_r_small.png
BTN_REC_RED_SMALL_HOVER=#@#Images\Buttons\btn_rec_r_small_hover.png

BTN_RES=#@#Images\Buttons\btn_res.png

BTN_SL=#@#Images\Buttons\btn_sl.png
BTN_SL_HOVER=#@#Images\Buttons\btn_sl_hover.png

BTN_TM_BLUE=#@#Images\Buttons\btn_tm_b.png
BTN_TM_BLUE_HOVER=#@#Images\Buttons\btn_tm_b_hover.png
BTN_TM_BROWN=#@#Images\Buttons\btn_tm_br.png
BTN_TM_BROWN_HOVER=#@#Images\Buttons\btn_tm_br_hover.png
BTN_TM_GREEN=#@#Images\Buttons\btn_tm_gr.png
BTN_TM_GREEN_HOVER=#@#Images\Buttons\btn_tm_gr_hover.png
BTN_TM_RED=#@#Images\Buttons\btn_tm_r.png
BTN_TM_RED_HOVER=#@#Images\Buttons\btn_tm_r_hover.png
BTN_TM_MENU=#@#Images\Buttons\btn_tm_menu.png
BTN_TM_MENU_HOVER=#@#Images\Buttons\btn_tm_menu_hover.png
BTN_TM_MENU_RED=#@#Images\Buttons\btn_tm_menu_r.png
BTN_TM_MENU_RED_HOVER=#@#Images\Buttons\btn_tm_menu_r_hover.png

BTN_TRANS=#@#Images\Buttons\btn_trans.png
BTN_TRANS_HOVER=#@#Images\Buttons\btn_trans_hover.png

;NOT IN USE IN THIS VERSION==================================================
BTN_L_1=#@#Images\Main\Launcher\btn.png
BTN_L_2=#@#Images\Main\Launcher\btn2.png
BTN_L_3=#@#Images\Main\Launcher\btn3.png
BTN_L_4=#@#Images\Main\Launcher\btn4.png
BTN_L_5=#@#Images\Main\Launcher\btn5.png












;################################################################################################################################################################################
;DECO============================================================================================================================================================================
;################################################################################################################################################################################

DECO_USR1=#@#Images\Environment\Animations\User\
DECO_USR2=#@#Images\Environment\deco_usr2.png
DECO_USR3=#@#Images\Environment\deco_usr3.png

DECO_TIME=#@#Images\Environment\deco_time.png

DECO_NEWS1=#@#Images\Environment\deco_news1.png
DECO_NEWS2=#@#Images\Environment\deco_news2.png
DECO_NEWS3=#@#Images\Environment\Animations\Feeds\
DECO_NEWS4=#@#Images\Environment\deco_news4.png

DECO_WEATHER=#@#Images\Environment\deco_pkt_weather.png 

DECO_MEDIA=#@#Images\Environment\deco_media.png

DECO_CPU=#@#Images\Internals\deco_cpu.png
DECO_MB1=#@#Images\Internals\deco_mb_1.png
DECO_MB2=#@#Images\Internals\Animations\board\
DECO_NW=#@#Images\Internals\deco_nw.png
DECO_PRO=#@#Images\Internals\deco_pro.png



;################################################################################################################################################################################
;BARS/GRAPHS/ROUNDLINES/LINES====================================================================================================================================================
;################################################################################################################################################################################

BAR_MB_BG=#@#Images\Internals\bar_mb.png
BAR_MB_COLOR=#@#Images\Internals\bar_mb_r.png

BAR_RAM_BG=#@#Images\Internals\bar_ram.png
BAR_RAM_COLOR=#@#Images\Internals\bar_ram_b.png
SCALE_RAM=#@#Images\Internals\scale_ram.png

ROUND_CPU=#@#Images\Internals\round_cpu.png
ROUND_GPU=#@#Images\Internals\round_gpu.png

BAR_MEDIA_BLUE=#@#Images\Environment\bar_media_b.png
BAR_MEDIA_RED=#@#Images\Environment\bar_media_r.png
BAR_MEDIA_YELLOW=#@#Images\Environment\bar_media_y.png

BAR_HDD_BG=#@#Images\Storage\bar_hdd_bg.png
BAR_HDD=#@#Images\Storage\bar_hdd.png
BAR_HDD_SMALL_BG=#@#Images\Storage\bar_small_hdd_bg.png
BAR_HDD_SMALL_BLUE=#@#Images\Storage\bar_small_hdd_b.png
BAR_HDD_SMALL_RED=#@#Images\Storage\bar_small_hdd_r.png
BAR_NET_BG=#@#Images\Storage\bar_net_bg.png
BAR_NET=#@#Images\Storage\bar_net.png
BAR_NET_SMALL_BG=#@#Images\Storage\bar_small_net_bg.png
BAR_NET_SMALL_BLUE=#@#Images\Storage\bar_small_net_b.png
BAR_NET_SMALL_RED=#@#Images\Storage\bar_small_net_r.png
BAR_USB_BG=#@#Images\Storage\bar_usb_bg.png
BAR_USB=#@#Images\Storage\bar_usb.png
BAR_USB_SMALL_BG=#@#Images\Storage\bar_small_usb_bg.png
BAR_USB_SMALL_BLUE=#@#Images\Storage\bar_small_usb_b.png
BAR_USB_SMALL_RED=#@#Images\Storage\bar_small_usb_r.png