[Variables]
Coul1=[#VVS1# CurC1 SolidColor "255,255,250"][!UpdateMeter CurC1]#RGSPC#
Coul2=[#VVS1# CurC1 SolidColor "255,255,0"][!UpdateMeter CurC1]#RGSPC#
Coul3=[#VVS1# CurC1 SolidColor "255,153,0,255"][!UpdateMeter CurC1]#RGSPC#
Coul4=[#VVS1# CurC1 SolidColor "255,27,10"][!UpdateMeter CurC1]#RGSPC#
Coul5=[#VVS1# CurC1 SolidColor "255,0,255"][!UpdateMeter CurC1]#RGSPC#
Coul6=[#VVS1# CurC1 SolidColor "236,0,140"][!UpdateMeter CurC1]#RGSPC#
Coul7=[#VVS1# CurC1 SolidColor "201,255,92, 255"][!UpdateMeter CurC1]#RGSPC#
Coul8=[#VVS1# CurC1 SolidColor "187,187,176,255"][!UpdateMeter CurC1]#RGSPC#
Coul9=[#VVS1# CurC1 SolidColor "161,0,253"][!UpdateMeter CurC1]#RGSPC#
Coul10=[#VVS1# CurC1 SolidColor "140,220,57"][!UpdateMeter CurC1]#RGSPC#
Coul11=[#VVS1# CurC1 SolidColor "161,0,79"][!UpdateMeter CurC1]#RGSPC#
Coul12=[#VVS1# CurC1 SolidColor "134,108,155"][!UpdateMeter CurC1]#RGSPC#
Coul13=[#VVS1# CurC1 SolidColor "252,252,252"][!UpdateMeter CurC1]#RGSPC#
Coul14=[#VVS1# CurC1 SolidColor "130, 227, 113, 89"][!UpdateMeter CurC1]#RGSPC#
Coul15=[#VVS1# CurC1 SolidColor "128,128,64"][!UpdateMeter CurC1]#RGSPC#
Coul16=[#VVS1# CurC1 SolidColor "128,64,0,255"][!UpdateMeter CurC1]#RGSPC#
Coul17=[#VVS1# CurC1 SolidColor "98,46,105"][!UpdateMeter CurC1]#RGSPC#
Coul18=[#VVS1# CurC1 SolidColor "64,128,128"][!UpdateMeter CurC1]#RGSPC#
Coul19=[#VVS1# CurC1 SolidColor "64,0,128"][!UpdateMeter CurC1]#RGSPC#
Coul20=[#VVS1# CurC1 SolidColor "64,153,224"][!UpdateMeter CurC1]#RGSPC#
Coul21=[#VVS1# CurC1 SolidColor "0, 171, 255, 255"][!UpdateMeter CurC1]#RGSPC#
Coul22=[#VVS1# CurC1 SolidColor "0,128,192"][!UpdateMeter CurC1]#RGSPC#
Coul23=[#VVS1# CurC1 SolidColor "0,128,0"][!UpdateMeter CurC1]#RGSPC#
Coul24=[#VVS1# CurC1 SolidColor "0,0,255"][!UpdateMeter CurC1]#RGSPC#
Coul25=[#VVS1# CurC1 SolidColor "0,0,0"][!UpdateMeter CurC1]#RGSPC#
Coul26=[#VVS1# CurC1 SolidColor "60,60,60"][!UpdateMeter CurC1]#RGSPC#
Coul27=[#VVS1# CurC1 SolidColor "225,225,225"][!UpdateMeter CurC1]#RGSPC#
Coul28=[#VVS1# CurC1 SolidColor "102,131,144"][!UpdateMeter CurC1]#RGSPC#
Coul29=[#VVS1# CurC1 SolidColor "208,52,56"][!UpdateMeter CurC1]#RGSPC#
Coul30=[#VVS1# CurC1 SolidColor "253,108,63"][!UpdateMeter CurC1]#RGSPC#
Coul31=[#VVS1# CurC1 SolidColor "249,78,124"][!UpdateMeter CurC1]#RGSPC#
Coul32=[#VVS1# CurC1 SolidColor "164,52,99"][!UpdateMeter CurC1]#RGSPC#
Coul33=[#VVS1# CurC1 SolidColor "219,179,40"][!UpdateMeter CurC1]#RGSPC#
Coul34=[#VVS1# CurC1 SolidColor "161,197,4"][!UpdateMeter CurC1]#RGSPC#
Coul35=[#VVS1# CurC1 SolidColor "33,115,70"][!UpdateMeter CurC1]#RGSPC#
Coul36=[#VVS1# CurC1 SolidColor "47,210,6"][!UpdateMeter CurC1]#RGSPC#
Coul37=[#VVS1# CurC1 SolidColor "3,208,252"][!UpdateMeter CurC1]#RGSPC#
Coul38=[#VVS1# CurC1 SolidColor "52,92,252"][!UpdateMeter CurC1]#RGSPC#
Coul39=[#VVS1# CurC1 SolidColor "57,64,197"][!UpdateMeter CurC1]#RGSPC#
Cout1=[#VVS1# CurC2 SolidColor "255,255,250"][!UpdateMeter CurC2]#RGSPC#
Cout2=[#VVS1# CurC2 SolidColor "255,255,0"][!UpdateMeter CurC2]#RGSPC#
Cout3=[#VVS1# CurC2 SolidColor "255,153,0,255"][!UpdateMeter CurC2]#RGSPC#
Cout4=[#VVS1# CurC2 SolidColor "255,27,10"][!UpdateMeter CurC2]#RGSPC#
Cout5=[#VVS1# CurC2 SolidColor "255,0,255"][!UpdateMeter CurC2]#RGSPC#
Cout6=[#VVS1# CurC2 SolidColor "236,0,140"][!UpdateMeter CurC2]#RGSPC#
Cout7=[#VVS1# CurC2 SolidColor "201,255,92, 255"][!UpdateMeter CurC2]#RGSPC#
Cout8=[#VVS1# CurC2 SolidColor "187,187,176,255"][!UpdateMeter CurC2]#RGSPC#
Cout9=[#VVS1# CurC2 SolidColor "161,0,253"][!UpdateMeter CurC2]#RGSPC#
Cout10=[#VVS1# CurC2 SolidColor "140,220,57"][!UpdateMeter CurC2]#RGSPC#
Cout11=[#VVS1# CurC2 SolidColor "161,0,79"][!UpdateMeter CurC2]#RGSPC#
Cout12=[#VVS1# CurC2 SolidColor "134,108,155"][!UpdateMeter CurC2]#RGSPC#
Cout13=[#VVS1# CurC2 SolidColor "252,252,252"][!UpdateMeter CurC2]#RGSPC#
Cout14=[#VVS1# CurC2 SolidColor "130, 227, 113, 89"][!UpdateMeter CurC2]#RGSPC#
Cout15=[#VVS1# CurC2 SolidColor "128,128,64"][!UpdateMeter CurC2]#RGSPC#
Cout16=[#VVS1# CurC2 SolidColor "128,64,0,255"][!UpdateMeter CurC2]#RGSPC#
Cout17=[#VVS1# CurC2 SolidColor "98,46,105"][!UpdateMeter CurC2]#RGSPC#
Cout18=[#VVS1# CurC2 SolidColor "64,128,128"][!UpdateMeter CurC2]#RGSPC#
Cout19=[#VVS1# CurC2 SolidColor "64,0,128"][!UpdateMeter CurC2]#RGSPC#
Cout20=[#VVS1# CurC2 SolidColor "64,153,224"][!UpdateMeter CurC2]#RGSPC#
Cout21=[#VVS1# CurC2 SolidColor "0, 171, 255, 255"][!UpdateMeter CurC2]#RGSPC#
Cout22=[#VVS1# CurC2 SolidColor "0,128,192"][!UpdateMeter CurC2]#RGSPC#
Cout23=[#VVS1# CurC2 SolidColor "0,128,0"][!UpdateMeter CurC2]#RGSPC#
Cout24=[#VVS1# CurC2 SolidColor "0,0,255"][!UpdateMeter CurC2]#RGSPC#
Cout25=[#VVS1# CurC2 SolidColor "0,0,0"][!UpdateMeter CurC2]#RGSPC#
Cout26=[#VVS1# CurC2 SolidColor "60,60,60"][!UpdateMeter CurC2]#RGSPC#
Cout27=[#VVS1# CurC2 SolidColor "225,225,225"][!UpdateMeter CurC2]#RGSPC#
Cout28=[#VVS1# CurC2 SolidColor "102,131,144"][!UpdateMeter CurC2]#RGSPC#
Cout29=[#VVS1# CurC2 SolidColor "208,52,56"][!UpdateMeter CurC2]#RGSPC#
Cout30=[#VVS1# CurC2 SolidColor "253,108,63"][!UpdateMeter CurC2]#RGSPC#
Cout31=[#VVS1# CurC2 SolidColor "249,78,124"][!UpdateMeter CurC2]#RGSPC#
Cout32=[#VVS1# CurC2 SolidColor "164,52,99"][!UpdateMeter CurC2]#RGSPC#
Cout33=[#VVS1# CurC2 SolidColor "219,179,40"][!UpdateMeter CurC2]#RGSPC#
Cout34=[#VVS1# CurC2 SolidColor "161,197,4"][!UpdateMeter CurC2]#RGSPC#
Cout35=[#VVS1# CurC2 SolidColor "33,115,70"][!UpdateMeter CurC2]#RGSPC#
Cout36=[#VVS1# CurC2 SolidColor "47,210,6"][!UpdateMeter CurC2]#RGSPC#
Cout37=[#VVS1# CurC2 SolidColor "3,208,252"][!UpdateMeter CurC2]#RGSPC#
Cout38=[#VVS1# CurC2 SolidColor "52,92,252"][!UpdateMeter CurC2]#RGSPC#
Cout39=[#VVS1# CurC2 SolidColor "57,64,197"][!UpdateMeter CurC2]#RGSPC#
Coup1=[#VVS1# CurC3 SolidColor "255,255,250"][!UpdateMeter CurC3]#RGSPC#
Coup2=[#VVS1# CurC3 SolidColor "255,255,0"][!UpdateMeter CurC3]#RGSPC#
Coup3=[#VVS1# CurC3 SolidColor "255,153,0,255"][!UpdateMeter CurC3]#RGSPC#
Coup4=[#VVS1# CurC3 SolidColor "255,27,10"][!UpdateMeter CurC3]#RGSPC#
Coup5=[#VVS1# CurC3 SolidColor "255,0,255"][!UpdateMeter CurC3]#RGSPC#
Coup6=[#VVS1# CurC3 SolidColor "236,0,140"][!UpdateMeter CurC3]#RGSPC#
Coup7=[#VVS1# CurC3 SolidColor "201,255,92, 255"][!UpdateMeter CurC3]#RGSPC#
Coup8=[#VVS1# CurC3 SolidColor "187,187,176,255"][!UpdateMeter CurC3]#RGSPC#
Coup9=[#VVS1# CurC3 SolidColor "161,0,253"][!UpdateMeter CurC3]#RGSPC#
Coup10=[#VVS1# CurC3 SolidColor "140,220,57"][!UpdateMeter CurC3]#RGSPC#
Coup11=[#VVS1# CurC3 SolidColor "161,0,79"][!UpdateMeter CurC3]#RGSPC#
Coup12=[#VVS1# CurC3 SolidColor "134,108,155"][!UpdateMeter CurC3]#RGSPC#
Coup13=[#VVS1# CurC3 SolidColor "252,252,252"][!UpdateMeter CurC3]#RGSPC#
Coup14=[#VVS1# CurC3 SolidColor "130, 227, 113, 89"][!UpdateMeter CurC3]#RGSPC#
Coup15=[#VVS1# CurC3 SolidColor "128,128,64"][!UpdateMeter CurC3]#RGSPC#
Coup16=[#VVS1# CurC3 SolidColor "128,64,0,255"][!UpdateMeter CurC3]#RGSPC#
Coup17=[#VVS1# CurC3 SolidColor "98,46,105"][!UpdateMeter CurC3]#RGSPC#
Coup18=[#VVS1# CurC3 SolidColor "64,128,128"][!UpdateMeter CurC3]#RGSPC#
Coup19=[#VVS1# CurC3 SolidColor "64,0,128"][!UpdateMeter CurC3]#RGSPC#
Coup20=[#VVS1# CurC3 SolidColor "64,153,224"][!UpdateMeter CurC3]#RGSPC#
Coup21=[#VVS1# CurC3 SolidColor "0, 171, 255, 255"][!UpdateMeter CurC3]#RGSPC#
Coup22=[#VVS1# CurC3 SolidColor "0,128,192"][!UpdateMeter CurC3]#RGSPC#
Coup23=[#VVS1# CurC3 SolidColor "0,128,0"][!UpdateMeter CurC3]#RGSPC#
Coup24=[#VVS1# CurC3 SolidColor "0,0,255"][!UpdateMeter CurC3]#RGSPC#
Coup25=[#VVS1# CurC3 SolidColor "0,0,0"][!UpdateMeter CurC3]#RGSPC#
Coup26=[#VVS1# CurC3 SolidColor "60,60,60"][!UpdateMeter CurC3]#RGSPC#
Coup27=[#VVS1# CurC3 SolidColor "225,225,225"][!UpdateMeter CurC3]#RGSPC#
Coup28=[#VVS1# CurC3 SolidColor "102,131,144"][!UpdateMeter CurC3]#RGSPC#
Coup29=[#VVS1# CurC3 SolidColor "208,52,56"][!UpdateMeter CurC3]#RGSPC#
Coup30=[#VVS1# CurC3 SolidColor "253,108,63"][!UpdateMeter CurC3]#RGSPC#
Coup31=[#VVS1# CurC3 SolidColor "249,78,124"][!UpdateMeter CurC3]#RGSPC#
Coup32=[#VVS1# CurC3 SolidColor "164,52,99"][!UpdateMeter CurC3]#RGSPC#
Coup33=[#VVS1# CurC3 SolidColor "219,179,40"][!UpdateMeter CurC3]#RGSPC#
Coup34=[#VVS1# CurC3 SolidColor "161,197,4"][!UpdateMeter CurC3]#RGSPC#
Coup35=[#VVS1# CurC3 SolidColor "33,115,70"][!UpdateMeter CurC3]#RGSPC#
Coup36=[#VVS1# CurC3 SolidColor "47,210,6"][!UpdateMeter CurC3]#RGSPC#
Coup37=[#VVS1# CurC3 SolidColor "3,208,252"][!UpdateMeter CurC3]#RGSPC#
Coup38=[#VVS1# CurC3 SolidColor "52,92,252"][!UpdateMeter CurC3]#RGSPC#
Coup39=[#VVS1# CurC3 SolidColor "57,64,197"][!UpdateMeter CurC3]#RGSPC#
Couq1=[#VVS1# CurC4 SolidColor "255,255,250"][!UpdateMeter CurC4]#RGSPC#
Couq2=[#VVS1# CurC4 SolidColor "255,255,0"][!UpdateMeter CurC4]#RGSPC#
Couq3=[#VVS1# CurC4 SolidColor "255,153,0,255"][!UpdateMeter CurC4]#RGSPC#
Couq4=[#VVS1# CurC4 SolidColor "255,27,10"][!UpdateMeter CurC4]#RGSPC#
Couq5=[#VVS1# CurC4 SolidColor "255,0,255"][!UpdateMeter CurC4]#RGSPC#
Couq6=[#VVS1# CurC4 SolidColor "236,0,140"][!UpdateMeter CurC4]#RGSPC#
Couq7=[#VVS1# CurC4 SolidColor "201,255,92, 255"][!UpdateMeter CurC4]#RGSPC#
Couq8=[#VVS1# CurC4 SolidColor "187,187,176,255"][!UpdateMeter CurC4]#RGSPC#
Couq9=[#VVS1# CurC4 SolidColor "161,0,253"][!UpdateMeter CurC4]#RGSPC#
Couq10=[#VVS1# CurC4 SolidColor "140,220,57"][!UpdateMeter CurC4]#RGSPC#
Couq11=[#VVS1# CurC4 SolidColor "161,0,79"][!UpdateMeter CurC4]#RGSPC#
Couq12=[#VVS1# CurC4 SolidColor "134,108,155"][!UpdateMeter CurC4]#RGSPC#
Couq13=[#VVS1# CurC4 SolidColor "252,252,252"][!UpdateMeter CurC4]#RGSPC#
Couq14=[#VVS1# CurC4 SolidColor "130, 227, 113, 89"][!UpdateMeter CurC4]#RGSPC#
Couq15=[#VVS1# CurC4 SolidColor "128,128,64"][!UpdateMeter CurC4]#RGSPC#
Couq16=[#VVS1# CurC4 SolidColor "128,64,0,255"][!UpdateMeter CurC4]#RGSPC#
Couq17=[#VVS1# CurC4 SolidColor "98,46,105"][!UpdateMeter CurC4]#RGSPC#
Couq18=[#VVS1# CurC4 SolidColor "64,128,128"][!UpdateMeter CurC4]#RGSPC#
Couq19=[#VVS1# CurC4 SolidColor "64,0,128"][!UpdateMeter CurC4]#RGSPC#
Couq20=[#VVS1# CurC4 SolidColor "64,153,224"][!UpdateMeter CurC4]#RGSPC#
Couq21=[#VVS1# CurC4 SolidColor "0, 171, 255, 255"][!UpdateMeter CurC4]#RGSPC#
Couq22=[#VVS1# CurC4 SolidColor "0,128,192"][!UpdateMeter CurC4]#RGSPC#
Couq23=[#VVS1# CurC4 SolidColor "0,128,0"][!UpdateMeter CurC4]#RGSPC#
Couq24=[#VVS1# CurC4 SolidColor "0,0,255"][!UpdateMeter CurC4]#RGSPC#
Couq25=[#VVS1# CurC4 SolidColor "0,0,0"][!UpdateMeter CurC4]#RGSPC#
Couq26=[#VVS1# CurC4 SolidColor "60,60,60"][!UpdateMeter CurC4]#RGSPC#
Couq27=[#VVS1# CurC4 SolidColor "225,225,225"][!UpdateMeter CurC4]#RGSPC#
Couq28=[#VVS1# CurC4 SolidColor "102,131,144"][!UpdateMeter CurC4]#RGSPC#
Couq29=[#VVS1# CurC4 SolidColor "208,52,56"][!UpdateMeter CurC4]#RGSPC#
Couq30=[#VVS1# CurC4 SolidColor "253,108,63"][!UpdateMeter CurC4]#RGSPC#
Couq31=[#VVS1# CurC4 SolidColor "249,78,124"][!UpdateMeter CurC4]#RGSPC#
Couq32=[#VVS1# CurC4 SolidColor "164,52,99"][!UpdateMeter CurC4]#RGSPC#
Couq33=[#VVS1# CurC4 SolidColor "219,179,40"][!UpdateMeter CurC4]#RGSPC#
Couq34=[#VVS1# CurC4 SolidColor "161,197,4"][!UpdateMeter CurC4]#RGSPC#
Couq35=[#VVS1# CurC4 SolidColor "33,115,70"][!UpdateMeter CurC4]#RGSPC#
Couq36=[#VVS1# CurC4 SolidColor "47,210,6"][!UpdateMeter CurC4]#RGSPC#
Couq37=[#VVS1# CurC4 SolidColor "3,208,252"][!UpdateMeter CurC4]#RGSPC#
Couq38=[#VVS1# CurC4 SolidColor "52,92,252"][!UpdateMeter CurC4]#RGSPC#
Couq39=[#VVS1# CurC4 SolidColor "57,64,197"][!UpdateMeter CurC4]#RGSPC#

[PG3]
Group=G3
Hidden=1

[CT]
H=8
W=28
ToolTipType=1
UpdateDivider=-1
Group=G3
Hidden=1

[IMS]
Shape=Rectangle 1,0,33,13,1 | Fill Color #DA2# | Extend Balls2
Balls2=StrokeWidth 2 | Stroke LinearGradient Gradient4
Gradient4=80 | #FBC# ; 0.0 | #FBP# ; 1.0
UpdateDivider=-1

[Imcs1]
Meter=Shape
MeterStyle=IMS|PG3
X=166
Y=69

[IP51]
Meter=Shape
MeterStyle=PF1|PG3
Shape=Rectangle 0,0,44,14,2 | Fill LinearGradient GradientClo | Extend BallsClo
X=115
Y=70

[IP51co]
Meter=Shape
MeterStyle=PF1|PG3
Shape=Rectangle 0,0,65,14,2 | Fill LinearGradient GradientClo | Extend BallsClo
X=210
Y=70

[CSTI]
X=367
TooltipText=#T11P9#

[Ic1a]
Meter=Shape
MeterStyle=BRG|PG3|CSTI
Y=71
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Config\ColorSpectrum" "Config.ini"]

[Colo1]
Meter=String
MeterStyle=Style|STTI|PG3
Text=#T2P9#1: 
Y=70
UpdateDivider=-1

[CurC1]
Meter=Image
MeterStyle=CT
SolidColor=#FBB#
X=50r
Y=2r

[CColo1]
Meter=String
MeterStyle=Style|PG3
Text=#OACT# 
X=210
Y=-2r

[STPC]
X=21r
Y=r
AntiAlias=1
ToolTipType=1
UpdateDivider=-1
H=10
W=10
Group=G3
Hidden=1

[C125]
Meter=Image
MeterStyle=STPC
SolidColor=255,255,255,250
X=117
Y=92
LeftMouseUpAction=[#VVS# "FBB" "255,255,250" #@#Style.inc]#MTAJR1##Coul1#

[C225]
Meter=Image
MeterStyle=STPC
SolidColor=255,255,0
LeftMouseUpAction=[#VVS# "FBB" "255,255,0" #@#Style.inc]#MTAJR1##Coul2#

[C325]
Meter=Image
MeterStyle=STPC
SolidColor=255,153,0,255
LeftMouseUpAction=[#VVS# "FBB" "255,153,0,255" #@#Style.inc]#MTAJR1##Coul3#

[C425]
Meter=Image
MeterStyle=STPC
SolidColor=255,27,10
LeftMouseUpAction=[#VVS# "FBB" "255,27,10" #@#Style.inc]#MTAJR1##Coul4#

[C525]
Meter=Image
MeterStyle=STPC
SolidColor=255,0,255
LeftMouseUpAction=[#VVS# "FBB" "255,0,255" #@#Style.inc]#MTAJR1##Coul5#

[C623]
Meter=Image
MeterStyle=STPC
SolidColor=236,0,140
LeftMouseUpAction=[#VVS# "FBB" "236,0,140" #@#Style.inc]#MTAJR1##Coul6#

[C720]
Meter=Image
MeterStyle=STPC
SolidColor=201,255,92, 255
LeftMouseUpAction=[#VVS# "FBB" "201,255,92, 255" #@#Style.inc]#MTAJR1##Coul7#

[C818]
Meter=Image
MeterStyle=STPC
SolidColor=187,187,176,255
LeftMouseUpAction=[#VVS# "FBB" "187,187,176,255" #@#Style.inc]#MTAJR1##Coul8#

[C916]
Meter=Image
MeterStyle=STPC
SolidColor=161,0,253
LeftMouseUpAction=[#VVS# "FBB" "161,0,253" #@#Style.inc]#MTAJR1##Coul9#

[C1014]
Meter=Image
MeterStyle=STPC
SolidColor=140,220,57
LeftMouseUpAction=[#VVS# "FBB" "140,220,57" #@#Style.inc]#MTAJR1##Coul10#

[T101]
Meter=Image
MeterStyle=STPC
SolidColor=161,0,79
LeftMouseUpAction=[#VVS# "FBB" "161,0,79" #@#Style.inc]#MTAJR1##Coul11#

[C111]
Meter=Image
MeterStyle=STPC
SolidColor=134,108,155
LeftMouseUpAction=[#VVS# "FBB" "134,108,155" #@#Style.inc]#MTAJR1##Coul12#

[T111]
Meter=Image
MeterStyle=STPC
SolidColor=252,252,252
LeftMouseUpAction=[#VVS# "FBB" "252,252,252" #@#Style.inc]#MTAJR1##Coul13#

[C121]
Meter=Image
MeterStyle=STPC
SolidColor=130, 227, 113, 89
X=117
Y=15r
LeftMouseUpAction=[#VVS# "FBB" "130, 227, 113, 89" #@#Style.inc]#MTAJR1##Coul14#

[C131]
Meter=Image
MeterStyle=STPC
SolidColor=128,128,64
LeftMouseUpAction=[#VVS# "FBB" "128,128,64" #@#Style.inc]#MTAJR1##Coul16#

[C141]
Meter=Image
MeterStyle=STPC
SolidColor=128,64,0,255
LeftMouseUpAction=[#VVS# "FBB" "128,64,0,255" #@#Style.inc]#MTAJR1##Coul16#

[C159]
Meter=Image
MeterStyle=STPC
SolidColor=98,46,105
LeftMouseUpAction=[#VVS# "FBB" "98,46,105" #@#Style.inc]#MTAJR1##Coul17#

[C166]
Meter=Image
MeterStyle=STPC
SolidColor=64,128,128
LeftMouseUpAction=[#VVS# "FBB" "64,128,128" #@#Style.inc]#MTAJR1##Coul18#

[C176]
Meter=Image
MeterStyle=STPC
SolidColor=64,0,128
LeftMouseUpAction=[#VVS# "FBB" "64,0,128" #@#Style.inc]#MTAJR1##Coul19#

[C184]
Meter=Image
MeterStyle=STPC
SolidColor=64,153,224
LeftMouseUpAction=[#VVS# "FBB" "64,153,224" #@#Style.inc]#MTAJR1##Coul20#

[C1901]
Meter=Image
MeterStyle=STPC
SolidColor=0, 171, 255, 255
LeftMouseUpAction=[#VVS# "FBB" "0, 171, 255, 255" #@#Style.inc]#MTAJR1##Coul21#

[C2001]
Meter=Image
MeterStyle=STPC
SolidColor=0,128,192
LeftMouseUpAction=[#VVS# "FBB" "0,128,192" #@#Style.inc]#MTAJR1##Coul22#

[C2101]
Meter=Image
MeterStyle=STPC
SolidColor=0,128,0
LeftMouseUpAction=[#VVS# "FBB" "0,128,0" #@#Style.inc]#MTAJR1##Coul23#

[C2200]
Meter=Image
MeterStyle=STPC
SolidColor=0,0,255
LeftMouseUpAction=[#VVS# "FBB" "0,0,255" #@#Style.inc]#MTAJR1##Coul24#

[C230]
Meter=Image
MeterStyle=STPC
SolidColor=0,0,0
LeftMouseUpAction=[#VVS# "FBB" "0,0,0" #@#Style.inc]#MTAJR1##Coul25#

[T230]
Meter=Image
MeterStyle=STPC
SolidColor=60,60,60
LeftMouseUpAction=[#VVS# "FBB" "60,60,60" #@#Style.inc]#MTAJR1##Coul26#

[T121]
Meter=Image
MeterStyle=STPC
SolidColor=225,225,225
X=117
Y=15r
LeftMouseUpAction=[#VVS# "FBB" "225,225,225" #@#Style.inc]#MTAJR1##Coul27#

[V230]
Meter=Image
MeterStyle=STPC
SolidColor=102,131,144
LeftMouseUpAction=[#VVS# "FBB" "102,131,144" #@#Style.inc]#MTAJR1##Coul28#

[V240]
Meter=Image
MeterStyle=STPC
SolidColor=208,52,56
LeftMouseUpAction=[#VVS# "FBB" "208,52,56" #@#Style.inc]#MTAJR1##Coul29#

[V250]
Meter=Image
MeterStyle=STPC
SolidColor=253,108,63
LeftMouseUpAction=[#VVS# "FBB" "253,108,63" #@#Style.inc]#MTAJR1##Coul30#

[V260]
Meter=Image
MeterStyle=STPC
SolidColor=249,78,124
LeftMouseUpAction=[#VVS# "FBB" "249,78,124" #@#Style.inc]#MTAJR1##Coul31#

[V270]
Meter=Image
MeterStyle=STPC
SolidColor=164,52,99
LeftMouseUpAction=[#VVS# "FBB" "164,52,99" #@#Style.inc]#MTAJR1##Coul32#

[V280]
Meter=Image
MeterStyle=STPC
SolidColor=219,179,40
LeftMouseUpAction=[#VVS# "FBB" "219,179,40" #@#Style.inc]#MTAJR1##Coul33#

[V290]
Meter=Image
MeterStyle=STPC
SolidColor=161,197,4
LeftMouseUpAction=[#VVS# "FBB" "161,197,4" #@#Style.inc]#MTAJR1##Coul34#

[V300]
Meter=Image
MeterStyle=STPC
SolidColor=33,115,70
LeftMouseUpAction=[#VVS# "FBB" "33,115,70" #@#Style.inc]#MTAJR1##Coul35#

[V310]
Meter=Image
MeterStyle=STPC
SolidColor=47,210,6
LeftMouseUpAction=[#VVS# "FBB" "47,210,6" #@#Style.inc]#MTAJR1##Coul36#

[V320]
Meter=Image
MeterStyle=STPC
SolidColor=3,208,252
LeftMouseUpAction=[#VVS# "FBB" "3,208,252" #@#Style.inc]#MTAJR1##Coul37#

[V330]
Meter=Image
MeterStyle=STPC
SolidColor=52,92,252
LeftMouseUpAction=[#VVS# "FBB" "52,92,252" #@#Style.inc]#MTAJR1##Coul38#

[V340]
Meter=Image
MeterStyle=STPC
SolidColor=57,64,197
LeftMouseUpAction=[#VVS# "FBB" "57,64,197" #@#Style.inc]#MTAJR1##Coul39#