[Ic2a]
Meter=Shape
MeterStyle=BRG|PG3|CSTI
Y=147
LeftMouseUpAction=[!ActivateConfig "#ROOTCONFIG#\Config\ColorSpectrum" "Config.ini"]

[Imcs2]
Meter=Shape
MeterStyle=IMS|PG3
X=166
Y=146

[IP52Co]
Meter=Shape
MeterStyle=PF1|PG3
Shape=Rectangle 0,0,65,14,2 | Fill LinearGradient GradientClo | Extend BallsClo
X=210
Y=146

[IP52]
Meter=Shape
MeterStyle=PF1|PG3
Shape=Rectangle 0,0,44,14,2 | Fill LinearGradient GradientClo | Extend BallsClo
X=115
Y=147

[Colo2]
Meter=String
MeterStyle=Style|STTI|PG3
Text=#T2P9#2: 
Y=148
UpdateDivider=-1

[CurC2]
Meter=Image
MeterStyle=CT
SolidColor=#DA1#
X=50r
Y=1r

[CColo2]
Meter=String
MeterStyle=Style|PG3
Text=#OACT# 
X=210
Y=-3r

[D125]
Meter=Image
MeterStyle=C125|STPC
X=117
Y=23r
LeftMouseUpAction=[#VVS# "DA1" "255,255,250" #@#Style.inc]#MTAJR1##Cout1#

[D225]
Meter=Image
MeterStyle=C225|STPC
LeftMouseUpAction=[#VVS# "DA1" "255,255,0" #@#Style.inc]#MTAJR1##Cout2#

[D325]
Meter=Image
MeterStyle=C325|STPC
LeftMouseUpAction=[#VVS# "DA1" "255,153,0,255" #@#Style.inc]#MTAJR1##Cout3#

[D425]
Meter=Image
MeterStyle=C425|STPC
LeftMouseUpAction=[#VVS# "DA1" "255,27,10" #@#Style.inc]#MTAJR1##Cout4#

[D525]
Meter=Image
MeterStyle=C525|STPC
LeftMouseUpAction=[#VVS# "DA1" "255,0,255" #@#Style.inc]#MTAJR1##Cout5#

[D623]
Meter=Image
MeterStyle=C623|STPC
LeftMouseUpAction=[#VVS# "DA1" "236,0,140" #@#Style.inc]#MTAJR1##Cout6#

[D720]
Meter=Image
MeterStyle=C720|STPC
LeftMouseUpAction=[#VVS# "DA1" "201,255,92, 255" #@#Style.inc]#MTAJR1##Cout7#

[D818]
Meter=Image
MeterStyle=C818|STPC
LeftMouseUpAction=[#VVS# "DA1" "187,187,176,255" #@#Style.inc]#MTAJR1##Cout8#

[D916]
Meter=Image
MeterStyle=C916|STPC
LeftMouseUpAction=[#VVS# "DA1" "161,0,253" #@#Style.inc]#MTAJR1##Cout9#

[D1014]
Meter=Image
MeterStyle=C1014|STPC
LeftMouseUpAction=[#VVS# "DA1" "140,220,57" #@#Style.inc]#MTAJR1##Cout10#

[T201]
Meter=Image
MeterStyle=T101|STPC
LeftMouseUpAction=[#VVS# "DA1" "161,0,79" #@#Style.inc]#MTAJR1##Cout11#

[D111]
Meter=Image
MeterStyle=C111|STPC
LeftMouseUpAction=[#VVS# "DA1" "134,108,155" #@#Style.inc]#MTAJR1##Cout12#

[D211]
Meter=Image
MeterStyle=T111|STPC
LeftMouseUpAction=[#VVS# "DA1" "252,252,252" #@#Style.inc]#MTAJR1##Cout13#

[D121]
Meter=Image
MeterStyle=C121|STPC
X=117
Y=15r
LeftMouseUpAction=[#VVS# "DA1" "130, 227, 113, 89" #@#Style.inc]#MTAJR1##Cout14#

[D131]
Meter=Image
MeterStyle=C131|STPC
LeftMouseUpAction=[#VVS# "DA1" "128,128,64" #@#Style.inc]#MTAJR1##Cout15#

[d141]
Meter=Image
MeterStyle=C141|STPC
LeftMouseUpAction=[#VVS# "DA1" "128,64,0,255" #@#Style.inc]#MTAJR1##Cout16#

[D159]
Meter=Image
MeterStyle=C159|STPC
LeftMouseUpAction=[#VVS# "DA1" "98,46,105" #@#Style.inc]#MTAJR1##Cout17#

[D166]
Meter=Image
MeterStyle=C166|STPC
LeftMouseUpAction=[#VVS# "DA1" "64,128,128" #@#Style.inc]#MTAJR1##Cout18#

[D176]
Meter=Image
MeterStyle=C176|STPC
LeftMouseUpAction=[#VVS# "DA1" "64,0,128" #@#Style.inc]#MTAJR1##Cout19#

[D184]
Meter=Image
MeterStyle=C184|STPC
LeftMouseUpAction=[#VVS# "DA1" "64,153,224" #@#Style.inc]#MTAJR1##Cout20#

[D1901]
Meter=Image
MeterStyle=C1901|STPC
LeftMouseUpAction=[#VVS# "DA1" "0, 171, 255, 255" #@#Style.inc]#MTAJR1##Cout21#

[D2001]
Meter=Image
MeterStyle=C2001|STPC
LeftMouseUpAction=[#VVS# "DA1" "0,128,192" #@#Style.inc]#MTAJR1##Cout22#

[D2101]
Meter=Image
MeterStyle=C2101|STPC
LeftMouseUpAction=[#VVS# "DA1" "0,128,0" #@#Style.inc]#MTAJR1##Cout23#

[D2200]
Meter=Image
MeterStyle=C2200|STPC
LeftMouseUpAction=[#VVS# "DA1" "0,0,255" #@#Style.inc]#MTAJR1##Cout24#

[C1230]
Meter=Image
MeterStyle=C230|STPC
LeftMouseUpAction=[#VVS# "DA1" "0,0,0" #@#Style.inc]#MTAJR1##Cout25#

[T1230]
Meter=Image
MeterStyle=T230|STPC
LeftMouseUpAction=[#VVS# "DA1" "60,60,60" #@#Style.inc]#MTAJR1##Cout26#

[T1121]
Meter=Image
MeterStyle=T121|STPC
X=117
Y=15r
LeftMouseUpAction=[#VVS# "DA1" "225,225,225" #@#Style.inc]#MTAJR1##Cout27#

[V1230]
Meter=Image
MeterStyle=V230|STPC
LeftMouseUpAction=[#VVS# "DA1" "102,131,144" #@#Style.inc]#MTAJR1##Cout28#

[V1240]
Meter=Image
MeterStyle=V240|STPC
LeftMouseUpAction=[#VVS# "DA1" "208,52,56" #@#Style.inc]#MTAJR1##Cout29#

[V1250]
Meter=Image
MeterStyle=V250|STPC
LeftMouseUpAction=[#VVS# "DA1" "253,108,63" #@#Style.inc]#MTAJR1##Cout30#

[V1260]
Meter=Image
MeterStyle=V260|STPC
LeftMouseUpAction=[#VVS# "DA1" "249,78,124" #@#Style.inc]#MTAJR1##Cout31#

[V1270]
Meter=Image
MeterStyle=V270|STPC
LeftMouseUpAction=[#VVS# "DA1" "164,52,99" #@#Style.inc]#MTAJR1##Cout32#

[V1280]
Meter=Image
MeterStyle=V280|STPC
LeftMouseUpAction=[#VVS# "DA1" "219,179,40" #@#Style.inc]#MTAJR1##Cout33#

[V1290]
Meter=Image
MeterStyle=V290|STPC
LeftMouseUpAction=[#VVS# "DA1" "161,197,4" #@#Style.inc]#MTAJR1##Cout34#

[V1300]
Meter=Image
MeterStyle=V300|STPC
LeftMouseUpAction=[#VVS# "DA1" "33,115,70" #@#Style.inc]#MTAJR1##Cout35#

[V1310]
Meter=Image
MeterStyle=V310|STPC
LeftMouseUpAction=[#VVS# "DA1" "47,210,6" #@#Style.inc]#MTAJR1##Cout36#

[V1320]
Meter=Image
MeterStyle=V320|STPC
LeftMouseUpAction=[#VVS# "DA1" "3,208,252" #@#Style.inc]#MTAJR1##Cout37#

[V1330]
Meter=Image
MeterStyle=V330|STPC
SolidColor=52,92,252
LeftMouseUpAction=[#VVS# "DA1" "52,92,252" #@#Style.inc]#MTAJR1##Cout38#

[V1340]
Meter=Image
MeterStyle=V340|STPC
LeftMouseUpAction=[#VVS# "DA1" "57,64,197" #@#Style.inc]#MTAJR1##Cout39#
