[Variables]
SHC1-1=D:\Outils\VLC\vlc.exe 
SHC1-2=VLC
Im1-1=#@#Images\Icones\Ap1.ico

SHC2-1=D:\Outils\Winamp\winamp.exe 
SHC2-2=Winamp
Im2-1=#@#Images\Icones\Ap2.ico

SHC3-1=D:\Outils\CCleaner\CCleaner64.exe 
SHC3-2=CCleaner
Im3-1=#@#Images\Icones\Ap3.ico

SHC4-1=D:\Outils\GIMP 2\bin\gimp-2.8.exe 
SHC4-2=Gimp
Im4-1=#@#Images\Icones\Ap4.ico

SHC5-1=D:\Outils\MiniTool Partition Wizard 10\partitionwizard.exe 
SHC5-2=MiniTool Partition Wizard 10
Im5-1=#@#Images\Icones\Ap5.ico

SHC6-1=D:\Outils\Opera\launcher.exe 
SHC6-2=Opera
Im6-1=#@#Images\Icones\Ap6.ico

SHC7-1=D:\Outils\Paint.Net\PaintDotNet.exe 
SHC7-2=Pant.Net
Im7-1=#@#Images\Icones\Ap7.ico

SHC8-1=D:\Outils\FastStone Image Viewer\FSViewer.exe 
SHC8-2=FastStone
Im8-1=#@#Images\Icones\Ap8.ico
