[Variables]

;HDD
OD=Open drive !
U=Used 
F=Free 
U1=Access
RE=Reading
WR=Writing
IT=Object(s)
LCRB=Left click opens the Trash
LCERB=Right click empty trash
LCADD=Left click shows details. Hide with the right click.
TOTA=Total
RecBin=Trash
REA=R
WRA=W
REAT=Cumulative Reads
WRAT=Cumulative Entries
Name=Name
PTRCP=Using the Trash  
DSTM=Filling rate
NDFC=Number of files
TDFC=Size of files
Vide=Empty
Paso=No objects
HDDAC1=Activity

;CPU
CPU=CPU used
ID=Not used
CPS=CPU speed
MHz=MHz
CP=CPU
TEMPE=Temperature
CPName=Processor Name
BUSP=System Bus
Mulr=Multiplier

;GPU
FSPD=Fan
GPUSD=GPU speed
MemSD=Memory Clock
Memgu=Memory used
Horlo=Clock
Memor=Memory
T33P1=GPU speed
T35P1=Speed
T36P1=Memory Speed
T38P1=Memory Size
GPU=GPU
MSIAFB=Requires MSIAfterBurner

;RAM & SWAP
OTM=Open task manager
RAU=Ram Used 
SWU=Swap used 
RA=RAM
SW=SWAP
RAF=Ram Free
SWF=Swap Free
TOMEMO=Total Memory

;Players
STP=Position of the song
POS=Position
P&P=Pause & Play
ST=Stop
PRE=Previous
NEXt=Next
PRG=Progression
PLAY=Play
DURA=Duration
Playr=Player
AlYe=Album - Year
PDIFO1=No information

;Volume
MU=Mute
VOL=Volume
VOLU=Increase Volume
VOLD=Lower volume
VOS=Volume mixer
CPA=Configuring Audio Devices
SS50=Set the sound to
NXDVE=Next device
VOLC=Left click increases the sound. Right click lowers the sound
NXDV1=Audio device
DR1=Right
GA1=Left

;Processes
PRO=Processes
TPP=Top processes
RRM1=Resource monitor
RRM2=Resources used by RainMeter

;Net
LI=Local IP
IN=In
OUT=Out
NT=Net
NTW=Network
WI=Wifi
Dowl=Download
Upld=Upload
Adapter=Adapter
DNSA=DNS Address
Gaway=Gateway
RESSTA=Right click resets statistics
WIUPD=Left click for an update
Wifi1=Broadcast name
Wifi2=Encryption
Wifi3=Supported band
RCOGO=Right click opens www.google.com
LCOS=Left click opens the search

;Gmail
NGM1=New mail
NGM2=No new mail
NGM3=Account
NGM4=New mails
T19P1=GMail User
T20P1=Username
T21P1=Password

;Weather
WEATH=Weather
RCOY1=Opens "weather.codes"
SWE=Simplified weather
Dem3=Today
Dem1=Tomorrow
High=High
Low=Low
T15P1=Weather Code
T16P1=Find your code on "weather.codes"
T17P1=Unit
T18P1=Temperature unit.#CRLF#m for Celsius or f for Fahrenheits
jpw="Sunday":"Sunday","Monday":"Monday","Tuesday":"Tuesday","Wednesday":"Wednesday","Thursday":"Thursday","Friday":"Friday","Saturday":"Saturday"
jpw1="Jan":"Jan","Feb":"Feb","Mar":"Mar","Apr":"Apr","May":"May","Jun":"Jun","Jul":"Jul","Aug":"Aug","Sep":"Sep","Oct":"Oct","Nov":"Nov","Dec":"Dec"
Sunrise=Sunrise
Sunset=Sunset
Humidi=Humidity
Current=Current
Preci1=Precipitation
Feel1=Feel
Moon=Moon
Wind=Wind
Pressure=Pressure

;CtrShut
HIBe=Hibernate
RESt=Restart
REST1=Advanced restart
SHUt=Shutdown
LOGo=Log off
Shutau1=Turn off your PC after
Shutau2=Left click starts the countdown. Right click cancels the action
Shutau3=Restart after
LOCWK=Lock the station

;Calendar
Mo=Mo
Tu=Tu
We=We
Th=Tu
Fr=Fr
Sa=Sa
Su=Su
SUND=Sunday
MOND=Monday
TUES=Tuesday
WEDN=Wednesday
THUR=Thursday
FRID=Friday
SATU=Saturday
Week=Week
Week+=Week
Calend=Calendar
January=January
February=February
March=March
April=April
May=May
June=June
July=July
August=August
September=September
October=October
November=November
December=December
Sun=Sun
Mon=Mon
Tue=Tue
Wed=Wed
Thu=Thu
Fri=Fri
Sat=Sat
Jan=Jan
Feb=Feb
Mar=Mar
Apr=Apr
Jun=Jun
Jul=Jul
Aug=Aug
Sep=Sep
Oct=Oct
Nov=Nov
Dec=Dec
CFANT=Click in order to open a note
J=D
W=W
JDLA=Day of year
Sur=Of
SC+=W
CF12=Left click activates the event indicator. Right click turns off.
CF1C=Left click hides events#CRLF#Right click shows events
CF2C=Left click shows next month
CF2C1=Left click shows the next month#CRLF#Right click changes the appearance of the event indicator
CF3C=Left click shows the previous month#CRLF#Right click changes the appearance of the day indicator
CF4C=Return to current month
CF5C=Left click opens the event file
CF9C=Click to open event file
CF10C=Left click shows / hides months (event files)
SHEV=Left click shows / hides events#CRLF#Right click changes the appearance of the note indicator

;Clock, Date, Time, Worldtime
D&T=Date & Time
D&THP=Date and hour panel
UP=Up
TOTW=Time over the world
CTTD=control.exe timedate.cpl
Day=Day
Date=Date
MTH=Month
Year=Year
UPT=Uptime
UPT1=Lifetime
Time=Time
TZNE=Time Zone
Day1=Day(s)
hour=Hour(s)
minutes=minutes
secondes=seconds
D=d

;Note, Folder, Picture, Wallpaper
OFD=Open directory
OMP=Directory of videos
MOVI=Movies
OMSP=Music Directory
MUSI=Musics
OPP=Image Directory
PICTU=Images
OPDO=Document Directory
Docum=Documents
OPDOw=Download directory

;Slideshow
KLCP=Left-click for preview
Siz=Size
StSli=Stop and restart the slideshow.
SALPP=Install as wallpaper
SBOF=Slideshow in full screen and slideshow as wallpaper
COCP=Click to change image
SGRIS=Gray color
AUTGS=Apply a gray tint to the images.
PSSKAS=Keep the proportions
Ratio=Proportions
PEFS1=Full screen
SLIINFO=Transition effects for slideshow

;Various
SYS=System
LCOP=Left click opens the menu. Right click closes the menu.
TOL=Tools
ADTS=Administrative Tools
STS=System Tools
DTOS=Miscellaneous Tools
WCalc=Calculator
WLD=Welcome
YACS=You are logged in since
YPHD=The name of your HDD is
UTSI=Total space is
HIUA=It uses
HFSIA=The free space is
T1P22=Left click opens the dock. Right click to close
HIDE=Hide
SHOW=Show
BOOK=Favorites
ALPS=All Programs
Run=Run
CBD1=you are using
CBD2=It is
CBD3=is logged in since
TPE1=Screen size
Uptuc=Update all
O/F=On / Off
Pour=for
Valrs=Values for

;Battery
BAP=Battery
BAPF=Battery filled
OPOP=Open Power Options
BAPF1=Sector
BAT1=No battery
BAT2=In charge
BAT3=Critical!
BAT4=Low
BAT5=Filled
BAT6=Remaining

;User
User=User
USFold=Folders
OUP=Open User Profile
PN=Name of the PC
MOD=Model
MAN=Manufacturer
PR=Product
OS=OS
INF=Information
Games=Games (backups)
Bureau=Desktop
RMUF=Rainmeter folder
CMB=Motherboard

;Presentation
T1P1=Configuration of the suite.
T3P1=Slideshow Directory
MIAS=Transition
T6P1=Transition delay between each image.
T7P1=Location of videos
T9P1=Music location
T11P1=Location of images
T13P1=Player
T14P1=Enter the name of your player. Choose your player between Winamp, AIMP, MusicBee, MediaMonkey, WMP, VLC ...

;Options
CLO=close
T3P10=Select
CPMAJ=Update
REFALL=Update all skins
Fondconf1=Click to apply
CF11C=Right click to update
T3P9=Left click opens the menu. Right click closes the menu.
CF6C=Left click displays / hides
STCCMAJ=Modify the shortcuts
T8P5=Change the icon
T9P6=Change picture
T5P8=change name
T6P8=Change info
OACT=Current option
Oui=Yes
Non=No

;Configuration
T2P9=Color
T4P9=Selected color
CDPDM=Current Color
T11P9=Other color choice#CRLF#with ColorSpectrum by Kaelri
T2P10=Font
Op1=None
Op2=Shadow
Op3=Border
Op4=Option for fonts
Op8=Effect
Op11=Option for text style
Op13=Bold
Op15=Italic
Op16=Click to setup
T3P16=Transparency
MTHes=Apply theme
MTHes2=Apply effect
T1PEFB1=Disables the effect
T1PEFB3=Disables themes
T1PEFB2=Click on an effect to reactivate it
T1P23=Selection effect
T2P23=Visual effect for themes.
DOTET=Effect "Dot"
ACEFFDOT=Activate the dots
DSEFFDOT=Disable dots
Select=Select
ACSELC=Enable Selection Effect
DESELC=Disable Selection Effect
CPCLC=Click here to apply the selected color
SPHY1=Color used for calendars (days of previous and following months)
T5P5=Change application and name#CRLF#Then, select the new icon.
T5P6=Click here to change the applications path.#CRLF#Then change the names (if needed) on this panel.
T5P7=Use the double left click to "travel" between disks & folders.
T0P0=Select the directory with the right click.
T0P1=Click on "Appl1" to change settings of the first application.
T0P2=Right click to select applications (current names & icons).
T0P3=Repeat the same thing for the others (click on "Appl2"...).
T6P5=Locations

;Evènements
Valen=Valentine's Day
14J=Fête Nationale (French)
Hawe=Halloween
TSNT=Toussaint
JDLAN=New Year's Day
25de=Christmas
FDTF=Labor Day
2FEV=Candlemas
1MRS=Great Mother's Day
8MRS=Victoire 1945
17Mp=St. Patrick's Day
14Ma=Ascension
24ma=Pentecôte
Printemps=Spring
Avril1=April Fool's Day
FDmere=Mother's Day
21ju=Father's Day - Summer
15Ao=Assumption
Summer=Summer
11Nov=Armistice 1918
21de=Winter
23seb=Autumn