[Variables]

;HDD
OD=Ouvrir le disque !
U=Utilisé 
U1=Accès
F=Libre 
RE=Lecture
WR=Ecriture
IT=Objet(s)
LCRB=Clic gauche ouvre la corbeille
LCERB=Clic droit vide la corbeille
LCADD=Clic gauche montre les détails. Clic droit cache
TOTA=Total
RecBin=Corbeille
REA=L
WRA=E
REAT=Lectures cumulées
WRAT=Ecritures cumulées
Name=Nom
PTRCP=Utilisation de la corbeille
DSTM=Taux de remplissage 
NDFC=Nombre de fichiers
TDFC=Taille des fichiers
Vide=Vide
Paso=Pas d'objets
HDDAC1=Activité

;CPU
CPU=CPU utilisé
ID=Inutilisé
CPS=Vitesse du CPU
MHz=MHz
CP=CPU
TEMPE=Température
CPName=Nom du processeur
BUSP=Bus système
Mulr=Multiplicateur

;GPU
FSPD=Ventilateur
GPUSD=Vitesse du GPU
MemSD=Horloge mémoire
Memgu=Mémoire utilisée
Horlo=Horloge
Memor=Mémoire
T33P1=Vitesse du GPU
T35P1=Vitesse 
T36P1=Vitesse de la mémoire
T38P1=Taille de la mémoire
GPU=GPU 
MSIAFB=Nécessite MSIAfterBurner

;RAM & SWAP
OTM=Ouvrir le Gestionnaire de tâches
RAU=Ram utilisée 
SWU=Swap utilisée 
RA=Ram
SW=Swap
RAF=Ram libre
SWF=Swap libre
TOMEMO=Mémoire totale

;Players
STP=Position du morceau
POS=Position
P&P=Pause & Jouer
ST=Stop
PRE=Précédent
NEXt=Suivant
PRG=Progression
PLAY=Jouer
DURA=Durée
Playr=Lecteur
AlYe=Album - Année
PDIFO1=Pas d'information

;Volume
MU=Muet
VOL=Volume
VOLU=Augmenter le volume 
VOLD=Baisser le volume 
VOS=Mélangeur de volume
CPA=Configuration des périphériques audio
SS50=Placer le son à
NXDVE=Périphérique suivant
VOLC=Clic gauche augmente le son. Clic droit baisse le son
NXDV1=Périphérique audio
DR1=Droite
GA1=Gauche

;Processus
PRO=Processus
TPP=Top processus
RRM1=Moniteur de ressources
RRM2=Ressources utilisées par RainMeter

;Net
LI=Local IP
IN=Entrant
OUT=Sortant
NT=Net
NTW=Network
WI=Wifi
Dowl=Réception
Upld=Emission
Adapter=Contrôleur
DNSA=Adresse DNS
Gaway=Passerelle
RESSTA=Clic droit réinitialise les statistiques
WIUPD=Clic gauche pour une mise à jour
Wifi1=Fournisseur
Wifi2=Cryptage
Wifi3=Type (norme)
RCOGO=Clic droit ouvre www.google.com
LCOS=Clic gauche ouvre la recherche

;Gmail
NGM1=Nouveau mail
NGM2=Pas de nouveau mail
NGM3=Compte
NGM4=Nouveaux mails
T19P1=Utilisateur GMail 
T20P1=Nom d'utilisateur
T21P1=Mot de passe

;Weather
WEATH=Météo
RCOY1=Ouvre "weather.codes"
SWE=Météo simplifiée
dem3=Aujourd'hui
dem1=Demain
High=Haute
Low=Basse
T15P1=Code météo
T16P1=Cherchez votre code sur weather.codes
T17P1=Unité 
T18P1=Unité de température.#CRLF#m pour Celsius ou f pour Fahrenheits
jpw="Sunday":"Dimanche","Monday":"Lundi","Tuesday":"Mardi","Wednesday":"Mercredi","Thursday":"Jeudi","Friday":"Vendredi","Saturday":"Samedi"
jpw1="Jan":"Jan","Feb":"Fév","Mar":"Mar","Apr":"Avr","May":"Mai","Jun":"Jui","Jul":"Jui","Aug":"Aoû","Sep":"Sep","Oct":"Oct","Nov":"Nov","Dec":"Déc"
Sunrise=Lever
Sunset=Coucher
Humidi=Humidité
Current=Actuelle
Preci1=Précipitation
Feel1=Ressenti
Moon=Lune
Wind=Vent
Pressure=Pression

;CtrShut
HIBE=Mise en veille
REST=Redémarrer
REST1=Redémarrage avancé
SHUT=Eteindre
LOGO=Déconnecter
Shutau1=Eteindre votre PC après
Shutau2=Clic gauche lance le compte à rebours. Clic droit annule l'action 
Shutau3=Redémarrer après
LOCWK=Verrouiller la station

;Calendar
Mo=Lu
Tu=Ma
We=Me
Th=Je
Fr=Ve
Sa=Sa
Su=Di
SUND=Dimanche
MOND=Lundi
TUES=Mardi
WEDN=Mercredi
THUR=Jeudi
FRID=Vendredi
SATU=Samedi
Week=Semaine
Week+=Semaine
Calend=Calendrier
January=Janvier
February=Fevrier
March=Mars
April=Avril
May=Mai
June=Juin
July=Juillet
August=Août
September=Septembre
October=Octobre
November=Novembre
December=Decembre
Sun=Dim
Mon=Lun
Tue=Mar
Wed=Mer
Thu=Jeu
Fri=Ven
Sat=Sam
Jan=Jan
Feb=Fev
Mar=Mar
Apr=Avr
Jun=Jui
Jul=Jui
Aug=Aoû
Sep=Sep
Oct=Oct
Nov=Nov
Dec=Dec
CFANT=Cliquez pour ouvrir une note
J=J
W=S
JDLA=Jour de l'année
Sur=sur
SC+=S
CF12=Clic gauche active l'indicateur d'évènements. Clic droit désactive.
CF1C=Clic gauche cache les évènements#CRLF#Clic droit montre les évènements
CF2C=Clic gauche montre le mois suivant
CF2C1=Clic gauche montre le mois suivant#CRLF#Clic droit change l'apparence de l'indicateur d'évènements
CF3C=Clic gauche montre le mois précédent#CRLF#Clic droit change l'apparence de l'indicateur du jour
CF4C=Revenir au mois en cours
CF5C=Clic gauche ouvre le fichier des évènements
CF9C=Cliquez pour ouvrir le fichier des évènements
CF10C=Clic gauche montre/cache les mois (fichiers des événements)
SHEV=Clic gauche affiche/cache les évènements#CRLF#Clic droit change l'apparence de l'indicateur de note

;Clock, Date, Time, Worldtime
D&T=Date & heure
D&THP=Panneau de la date & de l'heure
UP=Plus
TOTW=Heure à travers le monde
CTTD=control.exe timedate.cpl
Day=Jour
Date=Date
MTH=Mois
Year=Année
UPT=Durée session
UPT1=Durée
Time=Heure
TZNE=Fuseau horaire
Day1=Jour(s)
hour=Heure(s)
minutes=minutes
secondes=secondes
D=j

;Note, Folder, Picture, Wallpaper
OFD=Ouvrir le répertoire
OMP=Répertoire des vidéos
MOVI=Films
OMSP=Répertoire des musiques
MUSI=Musiques
OPP=Répertoire des images
PICTU=Images
OPDO=Répertoire des documents
Docum=Documents
OPDOw=Répertoire des téléchargements
 
;Slideshow
KLCP=Conservez un clic gauche pour une prévisualisation
Siz=Taille
StSli=Stop et redémarre le Diaporama.
SALPP=Installer en fond d'écran
SBOF=Diaporama en plein écran et diaporama en fond d'écran 
COCP=Cliquez pour changer d'image 
SGRIS=Teinte grise
AUTGS=Appliquer une teinte grise sur les images.
PSSKAS=Conserver les proportions 
Ratio=Proportions
PEFS1=Plein écran
SLIINFO=Effets de transition pour le diaporama

;Divers
SYS=Système
LCOP=Clic gauche ouvre le menu. Clic droit ferme le menu.
TOL=Outils
ADTS=Outils d'administration
STS=Outils système 
DTOS=Outils divers
WCalc=Calculatrice
WLD=Bienvenue
YACS=Vous êtes connecté depuis
YPHD=Le nom de votre HDD est
UTSI=L'espace total est de
HIUA=Il utilise 
HFSIA=L'espace libre est de
T1P22=Clic gauche ouvre le dock. Clic droit le ferme
HIDE=Cacher
SHOW=Montrer
BOOK=Favoris
ALPS=Tous les programmes
Run=Lancer
CBD1=vous utilisez
CBD2=Il est
CBD3=est connecté depuis
TPE1=Taille d'écran
uptuc=Tout mettre à jour
O/F=Marche/Arrêt
Pour=pour
Valrs=Valeurs pour

;Batterie
BAP=Batterie
BAPF=Batterie remplie
OPOP=Ouvrir les options d'alimentation
BAPF1=Secteur
BAT1=Pas de batterie
BAT2=En charge
BAT3=Critique !
BAT4=Faible
BAT5=Remplie
BAT6=Restant

;User
User=Utilisateur
USFold=dossiers
OUP=Ouvrir le profil de l'utilisateur 
PN=Nom du PC
MOD=Modèle
MAN=Constructeur
PR=Produit
OS=OS
INF=Informations
games=Jeux (sauvegardes)
Bureau=Bureau
RMUF=Dossier Rainmeter 
CMB=Carte mère

;Presentation
T1P1=Configuration de la suite.
T3P1=Répertoire du diaporama
MIAS=Transition
T6P1=Délai de transition entre chaque image. 
T7P1=Emplacement des vidéos
T9P1=Emplacement des musiques
T11P1=Emplacement des images
T13P1=Lecteur
T14P1=Entrez le nom de votre lecteur. Choisissez votre lecteur entre Winamp, AIMP, MusicBee, MediaMonkey, WMP, VLC...

;Options
CLO=fermer
T3P10=Sélectionner
CPMAJ=Mettre à jour
REFALL=Mettre à jour tous les skins
Fondconf1=Cliquez pour appliquer
CF11C=Clic droit pour mettre à jour
T3P9=Clic gauche ouvre le menu. Clic droit ferme le  menu.
CF6C=Clic gauche affiche/cache
STCCMAJ=Modifiez les raccourcis
T8P5=Changez l'icône
T9P6=Changer l'image
T5P8=changer le nom
T6P8=Changer les infos
OACT=Option actuelle
Oui=Oui
Non=Non

;Configuration
T2P9=Couleur
T4P9=Couleur sélectionnée
CDPDM=Couleur actuelle
T11P9=Autre choix de couleur#CRLF#avec ColorSpectrum de Kaelri
T2P10=Police
op1=Aucun
op2=Ombre
op3=Bordure
op4=Option pour les polices de caractère
op8=Effet
op11=Option pour le style des textes
op13=Gras
op15=Italique
op16=Cliquez pour configurer
T3P16=Transparence
MTHes=Appliquer le thème
MTHes2=Appliquer l'effet
T1PEFB1=Désactive l'effet
T1PEFB3=Désactive les thèmes
T1PEFB2=Cliquez sur un effet pour le réactiver
T1P23=Effet de sélection
T2P23=Effet visuel pour les thèmes.
DOTET=Effet "Dot"
ACEFFDOT=Activer les dots
DSEFFDOT=Désactiver les dots
Select=Sélection
ACSELC=Activer effet de sélection
DESELC=Désactiver effet de sélection 
CPCLC=Cliquez ici pour appliquer la couleur sélectionnée
SPHY1=Couleur utilisée pour les calendriers (jours des mois précédents et suivants)
T5P5=Changez l'application et le nom.#CRLF#Sélectionnez ensuite la nouvelle icone.
T5P6=Cliquez ici pour changer le chemin des applications#CRLF#Ensuite, changez les noms (si nécessaire) sur ce panneau.
T5P7=Utilisez le double clic pour "voyager" entres les disques et les dossiers.
T0P0=Sélectionnez le répertoire avec le bouton droit.
T0P1=Cliquez sur "Appl1" pour changer la première application.
T0P2=Bouton droit pour sélectionner les applications (noms actuels & icones).
T0P3=Répétez la même opération pour les autres (cliquez sur "Appl2"...).
T6P5=Emplacements

;Evènements
Valen=Saint Valentin
14J=Fête Nationale
Hawe=Halloween
TSNT=Toussaint
JDLAN=Jour de l'an
25de=Noël
FDTF=Fête du travail
2FEV=Chandeleur
1MRS=Fête des Grands-Mères
8MRS=Victoire 1945
17Mp=Saint Patrick
14Ma=Ascension
24ma=Pentecôte
Printemps=Printemps
Avril1=1er Avril :-).
FDmere=Fête des Mères
21ju=Fête des Pères - Eté
15Ao=Assomption
Summer=Eté
11Nov=Armistice 1918
21de=Hiver
23seb=Automne