[Variables]

;HDD
OD=Aprire il disco!
U=Usato
F=Libero
U1=Accesso
RE=Lettura
WR=Scrittura
IT=Oggetto(s)
LCRB=Clic sinistro del mouse si apre il cestino
LCERB=Fare clic destro svuotare il cestino
LCADD=guarda i dettagli. Hide con tasto destro del mouse.
TOTA=Totale
RecBin=Cestino
REA=L
WRA=S
REAT=Letture cumulativi
WRAT=Scritture cumulativi
Name=Nome
PTRCP=Uso del cestino  
DSTM=Filling rate
NDFC=Numero di file
TDFC=Dimensioni del file
Vide=Vuoto
Paso=Nessun oggetto
HDDAC1=Attività

;CPU
CPU=CPU utilizzata
ID=Inutilizzato
CPS=Velocità della CPU
MHz=MHz
CP=CPU
TEMPE=Temperatura
CPName=Processore Name
BUSP=Bus di sistema
Mulr=Moltiplicatore

;GPU
FSPD=Fan
GPUSD=GPU Velocità
MemSD=Clock di memoria
Memgu=Memoria utilizzata
Horlo=Clock
Memor=Memoria
T33P1=GPU Velocità
T35P1=Velocità
T36P1=Velocità memoria
T38P1=Capacità di memoria
GPU=GPU
MSIAFB=Richiede MSIAfterBurner

;RAM & SWAP
OTM=Aprire il Task Manager
RAU=Ram utilizzata 
SWU=Swap usato 
RA=RAM
SW=SWAP
RAF=Ram libero
SWF=Swap libero
TOMEMO=Memoria totale

;Players
STP=Posizione della canzone
POS=Posizione
P&P=Pausa & Gioca
ST=Stop
PRE=Precedente
NEXt=Avanti
PRG=Progresso
PLAY=Gioca
DURA=Durata
Playr=Player
AlYe=Album - Anno
PDIFO1=Nessuna informazione

;Volume
MU=Muto
VOL=Volume
VOLU=Volume Up
VOLD=Volume giù
VOS=Volume mixer
CPA=Dispositivi audio Configura
SS50=Imposta il suono
NXDVE=Dispositivo successivo
VOLC=Clic sinistro aumenta il suono. Fare clic destro verso il basso suono
NXDV1=Audio device
DR1=Destra
GA1=Sinistra

;Processes
PRO=Processo
TPP=Top Processo
RRM1=Resource monitor
RRM2=Risorse utilizzate per Rainmeter

;Net
LI=IP locale
IN=In
OUT=Out
NT=Net
NTW=Rete
WI=Wifi
Dowl=Ricevimento
Upld=Emissione
Adapter=Controller
DNSA=Indirizzo DNS
Gaway=Gateway
RESSTA=Statistiche clic destro azzera
WIUPD=Sinistra Clicca per un aggiornamento
Wifi1=Fornitore
Wifi2=Encryption
Wifi3=Supported band
RCOGO=Fare clic destro si apre www.google.com
LCOS=Clic sinistro si apre di ricerca

;Gmail
NGM1=Nuovo e-mail
NGM2=Nessun nuovo E-mail
NGM3=Account
NGM4=Nuovi messaggi
T19P1=Utente Gmail
T20P1=Nome utente
T21P1=Password

;Weather
WEATH=Meteo
RCOY1=Aperto "weather.codes"
SWE=Semplificato Meteo
Dem3=Oggi
Dem1=Domani
High=Alto
Low=Low
T15P1=Codice meteo
T16P1=Cerca il tuo codice su "weather.codes"
T17P1=Unità
T18P1=Temperatura unità.#CRLF#m per gradi Celsius or f per Fahrenheits
jpw="Sunday":"Domenica","Monday":"Lunedi","Tuesday":"Martedì","Wednesday":"Mercoledì","Thursday":"Giovedi","Friday":"Venerdì","Saturday":"Sabato"
jpw1="Jan":"Gen","Feb":"Feb","Mar":"Mar","Apr":"Apr","Jun":"Giu","Jul":"Lug","Aug":"Ago","Sep":"Set","Oct":"Ott","Nov":"Nov","Dec":"Dic"
Sunrise=Sunrise
Sunset=Sunset
Humidi=Umidità
Current=Corrente
Preci1=Piogge
Feel1=Feltro
Moon=Luna
Wind=Vento
Pressure=Pressione

;CtrShut
HIBe=Standby
RESt=Riavvio
REST1=Riavvio avanzata
SHUt=Spegnere
LOGo=Disconnect
Shutau1=Spegnere il PC dopo
Shutau2=Click sinistro lancia il conto alla rovescia. Fare clic destro annulla l'azione
Shutau3=Riavvio dopo
LOCWK=Stazione di blocco

;Calendar
Mo=Lu
Tu=Ma
We=Me
Th=Gi
Fr=Ve
Sa=Sa
Su=Do
SUND=Domenica
MOND=Lunedi
TUES=Martedì
WEDN=Mercoledì
THUR=Giovedi
FRID=Venerdì
SATU=Sabato
Week=Settimana
Week+=Settimana
Calend=Calendario
January=Gennaio
February=Febbraio
March=Marzo
April=Aprile
May=Maggio
June=Giugno
July=Luglio
August=Agosto
September=Settembre
October=Ottobre
November=Novembre
December=Dicembre
Sun=Dom
Mon=Lun
Tue=Mar
Wed=Mer
Thu=Gio
Fri=Ven
Sat=Sab
Jan=Gen
Feb=Feb
Mar=Mar
Apr=Apr
May=Mag
Jun=Giu
Jul=Lug
Aug=Ago
Sep=Set
Oct=Ott
Nov=Nov
Dec=Dic
CFANT=Fare clic per aprire una nota
J=G
W=S
JDLA=Giorno dell'anno
Sur=On
SC+=S
CF12=Click con sinistra attiva l'indicatore di evento. Fare clic destro fuori.
CF1C=Click sinistro nasconde di eventi di#CRLF# Click destro mostra gli eventi
CF2C=Click sinistra mostra il mese successivo
CF2C1=Clic sinistro mostra il mese successivo#CRLF#Fare clic destro cambia l'aspetto dell'indicatore dell'evento
CF3C=Click sinistra mostra il mese precedente#CRLF#Cambia l'aspetto dell'indicatore del giorno (clic destro)
CF4C=Ritorna al mese corrente 
CF5C=Sinistro del mouse si apre il file di eventi
CF9C=Fare clic per aprire il file di eventi
CF10C=Click sinistro mostra / nasconde il mese (i file di evento)
SHEV=Sinistra Clicca visualizzare / nascondere gli eventi#CRLF#Fare clic destro cambia l'aspetto dell'indicatore di nota

;Clock, Date, Time, Worldtime
D&T=Data e Ora
D&THP=Pannello data e ora
UP=Altro
TOTW=Tempo di tutto il mondo
CTTD=control.exe timedate.cpl
Day=Giorno
Date=Data
MTH=Mese
Year=Anno
UPT=Sessione di Tempo
UPT1=Durata
Time=Tempo
TZNE=Fuso orario
Day1=Giorno(s)
hour=ora
minutes=minuti
secondes=secondi
D=g

;Note, Folder, Picture, Wallpaper
OFD=Directory aperta
OMP=Elenco dei video
MOVI=Film
OMSP=Elenco della musica
MUSI=Musica
OPP=Elenco delle immagini
PICTU=Immagini
OPDO=Elenco dei Documenti
Docum=Documenti
OPDOw=Elenco di download

;Slideshow
KLCP=Tenere la sinistra clicca per un'anteprima
Siz=Dimensione
StSli=Arrestare e riavviare la presentazione.
SALPP=Installa come sfondo
SBOF=Sfondo della schermata presentazione completa
COCP=Clicca per cambiare immagine
SGRIS=Tinta grigio
AUTGS=Applicare a toni di grigio.
PSSKAS=Mantenere la proporzione
Ratio=Proporzioni
PEFS1=Schermo intero
SLIINFO=Effetti di transizione per le presentazioni

;Various
SYS=Sistema
LCOP=Sinistro del mouse apre il menu. Fare clic destro chiude il menu.
TOL=Strumenti
ADTS=Strumenti di amministrazione
STS=Strumenti di sistema
DTOS=Altri strumenti
WCalc=Calculator
WLD=Benvenuto
YACS=Sei stato registrato da
YPHD=Il nome del disco rigido
UTSI=Lo spazio totale è
HIUA=Esso utilizza
HFSIA=Lo spazio libero è
T1P22=Click sinistro del mouse si apre il dock. Fare clic con il chiude
HIDE=Nascondi
SHOW=Mostra
BOOK=Preferiti
ALPS=Tutti i programmi
Run=Inizio
CBD1=Si utilizza
CBD2=Il tempo è
CBD3=Collegato da
TPE1=Dimensione del display
Uptuc=Aggiorna tutto
O/F=On / Off
Pour=to
Valrs=I valori per

;Battery
BAP=Batteria
BAPF=Batteria Riempito
OPOP=Aprire le Opzioni risparmio energia
BAPF1=Settore
BAT1=Nessuna batteria
BAT2=Carica
BAT3=Critiche!
BAT4=Low
BAT5=Riempito
BAT6=Rimanenti

;User
User=Utente
USFold=Directory 
OUP=Profilo aperto
PN=PC Nome
MOD=Modello
MAN=Produttore
PR=Prodotto
OS=OS
INF=Informazioni
Games=Giochi (backups)
Bureau=Office
RMUF=Directory Rainmeter
CMB=Motherboard

;Presentation
T1P1=Configurazione Suite.
T3P1=Directory Viewer
MIAS=Transizione
T6P1=Tempo di transizione tra ogni immagine.
T7P1=Localizzazione video
T9P1=Localizzazione musica
T11P1=Localizzazione Immagine
T13P1=Player
T14P1=Inserire il nome del lettore. Scegliere tra il lettore Winamp, AIMP, MusicBee, MediaMonkey, WMP, VLC ...

;Options
CLO=vicino
T3P10=Seleziona
CPMAJ=Aggiornamento
REFALL=Aggiornare tutte le skins
Fondconf1=Fare clic per applicare
CF11C=Tasto destro del mouse per aggiornare
T3P9=Sinistro del mouse apre il menu. Fare clic destro chiude il menu.
CF6C=Sinistro del display Clicca / nascondere
STCCMAJ=Modificare i tasti di scelta rapida
T8P5=Cambiare l'icona
T9P6=Cambia immagine
T5P8=Cambiare il nome
T6P8=Modificare le informazioni
OACT=Opzione corrente
Oui=Si
Non=No

;Configuration
T2P9=Colore
T4P9=Colore selezionato
CDPDM=Colore corrente
T11P9=Altre scelte di colore con#CRLF#ColorSpectrum di Kaelri
T2P10=Polizia
Op1=No
Op2=Ombra
Op3=Border
Op4=Opzione per i font
Op8=effetto
Op11=Opzione per lo stile del testo
Op13=Bold
Op15=Corsivo
Op16=Clicca per configurare
T3P16=Trasparenza
MTHes=Applica tema
MTHes2=Applica effetto
T1PEFB1=Effetto Disabilita
T1PEFB3=Temi disabilita
T1PEFB2=Fare clic un effetto per selezionare 
T1P23=Effetto di selezione
T2P23=Effetto visivo per temi.
DOTET=Effetto  "Dot"
ACEFFDOT=Attiva dots
DSEFFDOT=Disabilita dots
Select=Selezione
ACSELC=Attiva effetto di selezione
DESELC=Disabilita effetto di selezione
CPCLC=Fare clic per applicare il colore selezionato
SPHY1=Colore utilizzato per i calendari (giorni precedenti e successivi al mese)
T5P5=Modificare l'applicazione e il nome.#CRLF#Quindi selezionare la nuova icona.
T5P6=Clicca qui per cambiare il percorso di applicazioni.#CRLF#Quindi modificare il nome (se necessario) su questo pannello.
T5P7=Utilizzare il doppio click sinistro per "viaggiare" tra i dischi e cartelle.
T0P0=Selezionare la directory con il tasto destro del mouse.
T0P1=Clicca su "APPL1" per modificare le impostazioni della prima applicazione.
T0P2=Tasto destro del mouse per selezionare le applicazioni (nomi e icone correnti).
T0P3=Ripetere la stessa cosa per gli altri (cliccare su "Appl2" ...).
T6P5=Sedi

;Evènements
Valen=Valentino
14J=Fête Nationale (French)
Hawe=Halloween
TSNT=Toussaint
JDLAN=Giorno di Capodanno
25de=Natale
FDTF=Festa del lavoro
2FEV=Chandeleur
1MRS=La festa della Grande Madre
8MRS=Vittoria 1945
17Mp=San Patrizio
14Ma=Ascension
24ma=Pentecoste
Printemps=Primavera
Avril1=1 aprile :-).
FDmere=Mother's Day
21ju=Father's Day - Estate
15Ao=Assunzione
Summer=Estate
11Nov=1918 Armistizio
21de=Inverno
23seb=Autunno