
[variables]



;column alignments for RAM, SWAP and HDD skins

headerxpos=330
percentxpos=530
absvaluexpos=535



; settings for separator lines that cover the top and bottom of the skins

seplincolor=150,150,150,255

seplinheight=1

seplinwidth=472



; styles for text: all occurences of text use this set of formatting options

txtfont="consolas"

txtsize=11

txtcolor=255,255,255,255

txteffect=Shadow

txteffectcolor=0,0,0,255



; colours for menu bar buttons: influences all collapsible menus and audio output toggle
hoverbarcolor=80,80,80,255
clickbarcolor=255,255,255,255

; height for the bars
clickhovbarH=20

;bar gaps (top of bar relative to bottom of text above it)
relbargap=1R

;gap between top of bar and top of its text label (text relative to top of bar)
relbartext=2r



; colors for all graphs

bargraphempty=80,80,80,255

bargraphfill=255,255,255,255

lingraphcolor=255,255,255,255

GRIDCOLOR=80,80,80,255



; dimensions for normal sized graphs: exclude removeable drives skins

lingraphheight=100

lingraphwidth=315

bargraphheight=10

bargraphwidth=315



; grid lines dimensions for normal size graphs: exclude removeable drives skins

initialX=3

initialY=20

horizgapY=10

horizGRIDH=1

horizGRIDW=315

;for network traffic skins
longhorizGRIDW=605








; dimensions for small sized graphs (removeable drives skins)

SMlingraphheight=70

SMlingraphwidth=250

SMbargraphheight=10

SMbargraphwidth=250


; grid lines dimensions for small sized graphs (removeable drives skins)

SMinitialX=15

SMinitialY=33

SMhorizgapY=7

SMhorizGRIDH=1

SMhorizGRIDW=250




; color of transparent black background: for all skins using a background (collapsible menus, welcome skin and google search bar input box)

transparcolor=0,0,0,220





menutitle_copytext="Copy text to clipboard"






